package com.ada.wuliu.mobile.front.dao;

import com.ada.wuliu.shipper.front.domian.invoice.AdwlInvoiceQualifications;
import com.ada.wuliu.shipper.front.domian.invoice.AdwlInvoiceQualificationsExample;
import java.sql.SQLException;
import java.util.List;

public interface AdwlInvoiceQualificationsDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    Long insert(AdwlInvoiceQualifications record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    int updateByPrimaryKey(AdwlInvoiceQualifications record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    int updateByPrimaryKeySelective(AdwlInvoiceQualifications record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    List selectByExample(AdwlInvoiceQualificationsExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    AdwlInvoiceQualifications selectByPrimaryKey(Long iqId) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    int deleteByExample(AdwlInvoiceQualificationsExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    int deleteByPrimaryKey(Long iqId) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    int countByExample(AdwlInvoiceQualificationsExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    int updateByExampleSelective(AdwlInvoiceQualifications record, AdwlInvoiceQualificationsExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    int updateByExample(AdwlInvoiceQualifications record, AdwlInvoiceQualificationsExample example) throws SQLException;
}