package com.ada.wuliu.mobile.front.dao;

import com.ada.wuliu.shipper.front.domian.invoice.AdwlInvoiceQualifications;
import com.ada.wuliu.shipper.front.domian.invoice.AdwlInvoiceQualificationsExample;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;
import java.util.List;

public class AdwlInvoiceQualificationsDAOImpl implements AdwlInvoiceQualificationsDAO {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public AdwlInvoiceQualificationsDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setSqlMapClient(SqlMapClient sqlMapClient) {
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public SqlMapClient getSqlMapClient() {
        return sqlMapClient;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public Long insert(AdwlInvoiceQualifications record) throws SQLException {
        Object newKey = sqlMapClient.insert("adwl_invoice_qualification.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public int updateByPrimaryKey(AdwlInvoiceQualifications record) throws SQLException {
        int rows = sqlMapClient.update("adwl_invoice_qualification.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public int updateByPrimaryKeySelective(AdwlInvoiceQualifications record) throws SQLException {
        int rows = sqlMapClient.update("adwl_invoice_qualification.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public List selectByExample(AdwlInvoiceQualificationsExample example) throws SQLException {
        List list = sqlMapClient.queryForList("adwl_invoice_qualification.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public AdwlInvoiceQualifications selectByPrimaryKey(Long iqId) throws SQLException {
        AdwlInvoiceQualifications key = new AdwlInvoiceQualifications();
        key.setIqId(iqId);
        AdwlInvoiceQualifications record = (AdwlInvoiceQualifications) sqlMapClient.queryForObject("adwl_invoice_qualification.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public int deleteByExample(AdwlInvoiceQualificationsExample example) throws SQLException {
        int rows = sqlMapClient.delete("adwl_invoice_qualification.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public int deleteByPrimaryKey(Long iqId) throws SQLException {
        AdwlInvoiceQualifications key = new AdwlInvoiceQualifications();
        key.setIqId(iqId);
        int rows = sqlMapClient.delete("adwl_invoice_qualification.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public int countByExample(AdwlInvoiceQualificationsExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("adwl_invoice_qualification.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public int updateByExampleSelective(AdwlInvoiceQualifications record, AdwlInvoiceQualificationsExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("adwl_invoice_qualification.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public int updateByExample(AdwlInvoiceQualifications record, AdwlInvoiceQualificationsExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("adwl_invoice_qualification.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private static class UpdateByExampleParms extends AdwlInvoiceQualificationsExample {
        private Object record;

        public UpdateByExampleParms(Object record, AdwlInvoiceQualificationsExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}