package com.ada.wuliu.mobile.front.dao;

import com.ada.wuliu.shipper.front.domian.LineLogistic;
import com.ada.wuliu.shipper.front.domian.LineLogisticExample;
import java.sql.SQLException;
import java.util.List;

public interface LineLogisticDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table adwl_line_logistic
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	Long insert(LineLogistic record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table adwl_line_logistic
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	int updateByPrimaryKey(LineLogistic record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table adwl_line_logistic
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	int updateByPrimaryKeySelective(LineLogistic record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table adwl_line_logistic
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	List selectByExample(LineLogisticExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table adwl_line_logistic
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	LineLogistic selectByPrimaryKey(Long llId) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table adwl_line_logistic
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	int deleteByExample(LineLogisticExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table adwl_line_logistic
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	int deleteByPrimaryKey(Long llId) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table adwl_line_logistic
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	int countByExample(LineLogisticExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table adwl_line_logistic
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	int updateByExampleSelective(LineLogistic record,
			LineLogisticExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table adwl_line_logistic
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	int updateByExample(LineLogistic record, LineLogisticExample example)
			throws SQLException;
}