package com.ada.wuliu.shipper.front.domian;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class LineLogisticExample {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table adwl_line_logistic
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table adwl_line_logistic
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table adwl_line_logistic
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public LineLogisticExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table adwl_line_logistic
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	protected LineLogisticExample(LineLogisticExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table adwl_line_logistic
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table adwl_line_logistic
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table adwl_line_logistic
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table adwl_line_logistic
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table adwl_line_logistic
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table adwl_line_logistic
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table adwl_line_logistic
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table adwl_line_logistic
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andLlIdIsNull() {
			addCriterion("ll_id is null");
			return this;
		}

		public Criteria andLlIdIsNotNull() {
			addCriterion("ll_id is not null");
			return this;
		}

		public Criteria andLlIdEqualTo(Long value) {
			addCriterion("ll_id =", value, "llId");
			return this;
		}

		public Criteria andLlIdNotEqualTo(Long value) {
			addCriterion("ll_id <>", value, "llId");
			return this;
		}

		public Criteria andLlIdGreaterThan(Long value) {
			addCriterion("ll_id >", value, "llId");
			return this;
		}

		public Criteria andLlIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ll_id >=", value, "llId");
			return this;
		}

		public Criteria andLlIdLessThan(Long value) {
			addCriterion("ll_id <", value, "llId");
			return this;
		}

		public Criteria andLlIdLessThanOrEqualTo(Long value) {
			addCriterion("ll_id <=", value, "llId");
			return this;
		}

		public Criteria andLlIdIn(List values) {
			addCriterion("ll_id in", values, "llId");
			return this;
		}

		public Criteria andLlIdNotIn(List values) {
			addCriterion("ll_id not in", values, "llId");
			return this;
		}

		public Criteria andLlIdBetween(Long value1, Long value2) {
			addCriterion("ll_id between", value1, value2, "llId");
			return this;
		}

		public Criteria andLlIdNotBetween(Long value1, Long value2) {
			addCriterion("ll_id not between", value1, value2, "llId");
			return this;
		}

		public Criteria andMsIdIsNull() {
			addCriterion("ms_id is null");
			return this;
		}

		public Criteria andMsIdIsNotNull() {
			addCriterion("ms_id is not null");
			return this;
		}

		public Criteria andMsIdEqualTo(Long value) {
			addCriterion("ms_id =", value, "msId");
			return this;
		}

		public Criteria andMsIdNotEqualTo(Long value) {
			addCriterion("ms_id <>", value, "msId");
			return this;
		}

		public Criteria andMsIdGreaterThan(Long value) {
			addCriterion("ms_id >", value, "msId");
			return this;
		}

		public Criteria andMsIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ms_id >=", value, "msId");
			return this;
		}

		public Criteria andMsIdLessThan(Long value) {
			addCriterion("ms_id <", value, "msId");
			return this;
		}

		public Criteria andMsIdLessThanOrEqualTo(Long value) {
			addCriterion("ms_id <=", value, "msId");
			return this;
		}

		public Criteria andMsIdIn(List values) {
			addCriterion("ms_id in", values, "msId");
			return this;
		}

		public Criteria andMsIdNotIn(List values) {
			addCriterion("ms_id not in", values, "msId");
			return this;
		}

		public Criteria andMsIdBetween(Long value1, Long value2) {
			addCriterion("ms_id between", value1, value2, "msId");
			return this;
		}

		public Criteria andMsIdNotBetween(Long value1, Long value2) {
			addCriterion("ms_id not between", value1, value2, "msId");
			return this;
		}

		public Criteria andLlTypeIsNull() {
			addCriterion("ll_type is null");
			return this;
		}

		public Criteria andLlTypeIsNotNull() {
			addCriterion("ll_type is not null");
			return this;
		}

		public Criteria andLlTypeEqualTo(String value) {
			addCriterion("ll_type =", value, "llType");
			return this;
		}

		public Criteria andLlTypeNotEqualTo(String value) {
			addCriterion("ll_type <>", value, "llType");
			return this;
		}

		public Criteria andLlTypeGreaterThan(String value) {
			addCriterion("ll_type >", value, "llType");
			return this;
		}

		public Criteria andLlTypeGreaterThanOrEqualTo(String value) {
			addCriterion("ll_type >=", value, "llType");
			return this;
		}

		public Criteria andLlTypeLessThan(String value) {
			addCriterion("ll_type <", value, "llType");
			return this;
		}

		public Criteria andLlTypeLessThanOrEqualTo(String value) {
			addCriterion("ll_type <=", value, "llType");
			return this;
		}

		public Criteria andLlTypeLike(String value) {
			addCriterion("ll_type like", value, "llType");
			return this;
		}

		public Criteria andLlTypeNotLike(String value) {
			addCriterion("ll_type not like", value, "llType");
			return this;
		}

		public Criteria andLlTypeIn(List values) {
			addCriterion("ll_type in", values, "llType");
			return this;
		}

		public Criteria andLlTypeNotIn(List values) {
			addCriterion("ll_type not in", values, "llType");
			return this;
		}

		public Criteria andLlTypeBetween(String value1, String value2) {
			addCriterion("ll_type between", value1, value2, "llType");
			return this;
		}

		public Criteria andLlTypeNotBetween(String value1, String value2) {
			addCriterion("ll_type not between", value1, value2, "llType");
			return this;
		}

		public Criteria andLlDepartureProvinceIsNull() {
			addCriterion("ll_departure_province is null");
			return this;
		}

		public Criteria andLlDepartureProvinceIsNotNull() {
			addCriterion("ll_departure_province is not null");
			return this;
		}

		public Criteria andLlDepartureProvinceEqualTo(String value) {
			addCriterion("ll_departure_province =", value,
					"llDepartureProvince");
			return this;
		}

		public Criteria andLlDepartureProvinceNotEqualTo(String value) {
			addCriterion("ll_departure_province <>", value,
					"llDepartureProvince");
			return this;
		}

		public Criteria andLlDepartureProvinceGreaterThan(String value) {
			addCriterion("ll_departure_province >", value,
					"llDepartureProvince");
			return this;
		}

		public Criteria andLlDepartureProvinceGreaterThanOrEqualTo(String value) {
			addCriterion("ll_departure_province >=", value,
					"llDepartureProvince");
			return this;
		}

		public Criteria andLlDepartureProvinceLessThan(String value) {
			addCriterion("ll_departure_province <", value,
					"llDepartureProvince");
			return this;
		}

		public Criteria andLlDepartureProvinceLessThanOrEqualTo(String value) {
			addCriterion("ll_departure_province <=", value,
					"llDepartureProvince");
			return this;
		}

		public Criteria andLlDepartureProvinceLike(String value) {
			addCriterion("ll_departure_province like", value,
					"llDepartureProvince");
			return this;
		}

		public Criteria andLlDepartureProvinceNotLike(String value) {
			addCriterion("ll_departure_province not like", value,
					"llDepartureProvince");
			return this;
		}

		public Criteria andLlDepartureProvinceIn(List values) {
			addCriterion("ll_departure_province in", values,
					"llDepartureProvince");
			return this;
		}

		public Criteria andLlDepartureProvinceNotIn(List values) {
			addCriterion("ll_departure_province not in", values,
					"llDepartureProvince");
			return this;
		}

		public Criteria andLlDepartureProvinceBetween(String value1,
				String value2) {
			addCriterion("ll_departure_province between", value1, value2,
					"llDepartureProvince");
			return this;
		}

		public Criteria andLlDepartureProvinceNotBetween(String value1,
				String value2) {
			addCriterion("ll_departure_province not between", value1, value2,
					"llDepartureProvince");
			return this;
		}

		public Criteria andLlDepartureCityIsNull() {
			addCriterion("ll_departure_city is null");
			return this;
		}

		public Criteria andLlDepartureCityIsNotNull() {
			addCriterion("ll_departure_city is not null");
			return this;
		}

		public Criteria andLlDepartureCityEqualTo(String value) {
			addCriterion("ll_departure_city =", value, "llDepartureCity");
			return this;
		}

		public Criteria andLlDepartureCityNotEqualTo(String value) {
			addCriterion("ll_departure_city <>", value, "llDepartureCity");
			return this;
		}

		public Criteria andLlDepartureCityGreaterThan(String value) {
			addCriterion("ll_departure_city >", value, "llDepartureCity");
			return this;
		}

		public Criteria andLlDepartureCityGreaterThanOrEqualTo(String value) {
			addCriterion("ll_departure_city >=", value, "llDepartureCity");
			return this;
		}

		public Criteria andLlDepartureCityLessThan(String value) {
			addCriterion("ll_departure_city <", value, "llDepartureCity");
			return this;
		}

		public Criteria andLlDepartureCityLessThanOrEqualTo(String value) {
			addCriterion("ll_departure_city <=", value, "llDepartureCity");
			return this;
		}

		public Criteria andLlDepartureCityLike(String value) {
			addCriterion("ll_departure_city like", value, "llDepartureCity");
			return this;
		}

		public Criteria andLlDepartureCityNotLike(String value) {
			addCriterion("ll_departure_city not like", value, "llDepartureCity");
			return this;
		}

		public Criteria andLlDepartureCityIn(List values) {
			addCriterion("ll_departure_city in", values, "llDepartureCity");
			return this;
		}

		public Criteria andLlDepartureCityNotIn(List values) {
			addCriterion("ll_departure_city not in", values, "llDepartureCity");
			return this;
		}

		public Criteria andLlDepartureCityBetween(String value1, String value2) {
			addCriterion("ll_departure_city between", value1, value2,
					"llDepartureCity");
			return this;
		}

		public Criteria andLlDepartureCityNotBetween(String value1,
				String value2) {
			addCriterion("ll_departure_city not between", value1, value2,
					"llDepartureCity");
			return this;
		}

		public Criteria andLlDepartureAreaIsNull() {
			addCriterion("ll_departure_area is null");
			return this;
		}

		public Criteria andLlDepartureAreaIsNotNull() {
			addCriterion("ll_departure_area is not null");
			return this;
		}

		public Criteria andLlDepartureAreaEqualTo(String value) {
			addCriterion("ll_departure_area =", value, "llDepartureArea");
			return this;
		}

		public Criteria andLlDepartureAreaNotEqualTo(String value) {
			addCriterion("ll_departure_area <>", value, "llDepartureArea");
			return this;
		}

		public Criteria andLlDepartureAreaGreaterThan(String value) {
			addCriterion("ll_departure_area >", value, "llDepartureArea");
			return this;
		}

		public Criteria andLlDepartureAreaGreaterThanOrEqualTo(String value) {
			addCriterion("ll_departure_area >=", value, "llDepartureArea");
			return this;
		}

		public Criteria andLlDepartureAreaLessThan(String value) {
			addCriterion("ll_departure_area <", value, "llDepartureArea");
			return this;
		}

		public Criteria andLlDepartureAreaLessThanOrEqualTo(String value) {
			addCriterion("ll_departure_area <=", value, "llDepartureArea");
			return this;
		}

		public Criteria andLlDepartureAreaLike(String value) {
			addCriterion("ll_departure_area like", value, "llDepartureArea");
			return this;
		}

		public Criteria andLlDepartureAreaNotLike(String value) {
			addCriterion("ll_departure_area not like", value, "llDepartureArea");
			return this;
		}

		public Criteria andLlDepartureAreaIn(List values) {
			addCriterion("ll_departure_area in", values, "llDepartureArea");
			return this;
		}

		public Criteria andLlDepartureAreaNotIn(List values) {
			addCriterion("ll_departure_area not in", values, "llDepartureArea");
			return this;
		}

		public Criteria andLlDepartureAreaBetween(String value1, String value2) {
			addCriterion("ll_departure_area between", value1, value2,
					"llDepartureArea");
			return this;
		}

		public Criteria andLlDepartureAreaNotBetween(String value1,
				String value2) {
			addCriterion("ll_departure_area not between", value1, value2,
					"llDepartureArea");
			return this;
		}

		public Criteria andLlDepartureNetworkIsNull() {
			addCriterion("ll_departure_network is null");
			return this;
		}

		public Criteria andLlDepartureNetworkIsNotNull() {
			addCriterion("ll_departure_network is not null");
			return this;
		}

		public Criteria andLlDepartureNetworkEqualTo(String value) {
			addCriterion("ll_departure_network =", value, "llDepartureNetwork");
			return this;
		}

		public Criteria andLlDepartureNetworkNotEqualTo(String value) {
			addCriterion("ll_departure_network <>", value, "llDepartureNetwork");
			return this;
		}

		public Criteria andLlDepartureNetworkGreaterThan(String value) {
			addCriterion("ll_departure_network >", value, "llDepartureNetwork");
			return this;
		}

		public Criteria andLlDepartureNetworkGreaterThanOrEqualTo(String value) {
			addCriterion("ll_departure_network >=", value, "llDepartureNetwork");
			return this;
		}

		public Criteria andLlDepartureNetworkLessThan(String value) {
			addCriterion("ll_departure_network <", value, "llDepartureNetwork");
			return this;
		}

		public Criteria andLlDepartureNetworkLessThanOrEqualTo(String value) {
			addCriterion("ll_departure_network <=", value, "llDepartureNetwork");
			return this;
		}

		public Criteria andLlDepartureNetworkLike(String value) {
			addCriterion("ll_departure_network like", value,
					"llDepartureNetwork");
			return this;
		}

		public Criteria andLlDepartureNetworkNotLike(String value) {
			addCriterion("ll_departure_network not like", value,
					"llDepartureNetwork");
			return this;
		}

		public Criteria andLlDepartureNetworkIn(List values) {
			addCriterion("ll_departure_network in", values,
					"llDepartureNetwork");
			return this;
		}

		public Criteria andLlDepartureNetworkNotIn(List values) {
			addCriterion("ll_departure_network not in", values,
					"llDepartureNetwork");
			return this;
		}

		public Criteria andLlDepartureNetworkBetween(String value1,
				String value2) {
			addCriterion("ll_departure_network between", value1, value2,
					"llDepartureNetwork");
			return this;
		}

		public Criteria andLlDepartureNetworkNotBetween(String value1,
				String value2) {
			addCriterion("ll_departure_network not between", value1, value2,
					"llDepartureNetwork");
			return this;
		}

		public Criteria andLlDepartureAddressIsNull() {
			addCriterion("ll_departure_address is null");
			return this;
		}

		public Criteria andLlDepartureAddressIsNotNull() {
			addCriterion("ll_departure_address is not null");
			return this;
		}

		public Criteria andLlDepartureAddressEqualTo(String value) {
			addCriterion("ll_departure_address =", value, "llDepartureAddress");
			return this;
		}

		public Criteria andLlDepartureAddressNotEqualTo(String value) {
			addCriterion("ll_departure_address <>", value, "llDepartureAddress");
			return this;
		}

		public Criteria andLlDepartureAddressGreaterThan(String value) {
			addCriterion("ll_departure_address >", value, "llDepartureAddress");
			return this;
		}

		public Criteria andLlDepartureAddressGreaterThanOrEqualTo(String value) {
			addCriterion("ll_departure_address >=", value, "llDepartureAddress");
			return this;
		}

		public Criteria andLlDepartureAddressLessThan(String value) {
			addCriterion("ll_departure_address <", value, "llDepartureAddress");
			return this;
		}

		public Criteria andLlDepartureAddressLessThanOrEqualTo(String value) {
			addCriterion("ll_departure_address <=", value, "llDepartureAddress");
			return this;
		}

		public Criteria andLlDepartureAddressLike(String value) {
			addCriterion("ll_departure_address like", value,
					"llDepartureAddress");
			return this;
		}

		public Criteria andLlDepartureAddressNotLike(String value) {
			addCriterion("ll_departure_address not like", value,
					"llDepartureAddress");
			return this;
		}

		public Criteria andLlDepartureAddressIn(List values) {
			addCriterion("ll_departure_address in", values,
					"llDepartureAddress");
			return this;
		}

		public Criteria andLlDepartureAddressNotIn(List values) {
			addCriterion("ll_departure_address not in", values,
					"llDepartureAddress");
			return this;
		}

		public Criteria andLlDepartureAddressBetween(String value1,
				String value2) {
			addCriterion("ll_departure_address between", value1, value2,
					"llDepartureAddress");
			return this;
		}

		public Criteria andLlDepartureAddressNotBetween(String value1,
				String value2) {
			addCriterion("ll_departure_address not between", value1, value2,
					"llDepartureAddress");
			return this;
		}

		public Criteria andLlDeparturePersonNameIsNull() {
			addCriterion("ll_departure_person_name is null");
			return this;
		}

		public Criteria andLlDeparturePersonNameIsNotNull() {
			addCriterion("ll_departure_person_name is not null");
			return this;
		}

		public Criteria andLlDeparturePersonNameEqualTo(String value) {
			addCriterion("ll_departure_person_name =", value,
					"llDeparturePersonName");
			return this;
		}

		public Criteria andLlDeparturePersonNameNotEqualTo(String value) {
			addCriterion("ll_departure_person_name <>", value,
					"llDeparturePersonName");
			return this;
		}

		public Criteria andLlDeparturePersonNameGreaterThan(String value) {
			addCriterion("ll_departure_person_name >", value,
					"llDeparturePersonName");
			return this;
		}

		public Criteria andLlDeparturePersonNameGreaterThanOrEqualTo(
				String value) {
			addCriterion("ll_departure_person_name >=", value,
					"llDeparturePersonName");
			return this;
		}

		public Criteria andLlDeparturePersonNameLessThan(String value) {
			addCriterion("ll_departure_person_name <", value,
					"llDeparturePersonName");
			return this;
		}

		public Criteria andLlDeparturePersonNameLessThanOrEqualTo(String value) {
			addCriterion("ll_departure_person_name <=", value,
					"llDeparturePersonName");
			return this;
		}

		public Criteria andLlDeparturePersonNameLike(String value) {
			addCriterion("ll_departure_person_name like", value,
					"llDeparturePersonName");
			return this;
		}

		public Criteria andLlDeparturePersonNameNotLike(String value) {
			addCriterion("ll_departure_person_name not like", value,
					"llDeparturePersonName");
			return this;
		}

		public Criteria andLlDeparturePersonNameIn(List values) {
			addCriterion("ll_departure_person_name in", values,
					"llDeparturePersonName");
			return this;
		}

		public Criteria andLlDeparturePersonNameNotIn(List values) {
			addCriterion("ll_departure_person_name not in", values,
					"llDeparturePersonName");
			return this;
		}

		public Criteria andLlDeparturePersonNameBetween(String value1,
				String value2) {
			addCriterion("ll_departure_person_name between", value1, value2,
					"llDeparturePersonName");
			return this;
		}

		public Criteria andLlDeparturePersonNameNotBetween(String value1,
				String value2) {
			addCriterion("ll_departure_person_name not between", value1,
					value2, "llDeparturePersonName");
			return this;
		}

		public Criteria andLlDeparturePhoneIsNull() {
			addCriterion("ll_departure_phone is null");
			return this;
		}

		public Criteria andLlDeparturePhoneIsNotNull() {
			addCriterion("ll_departure_phone is not null");
			return this;
		}

		public Criteria andLlDeparturePhoneEqualTo(String value) {
			addCriterion("ll_departure_phone =", value, "llDeparturePhone");
			return this;
		}

		public Criteria andLlDeparturePhoneNotEqualTo(String value) {
			addCriterion("ll_departure_phone <>", value, "llDeparturePhone");
			return this;
		}

		public Criteria andLlDeparturePhoneGreaterThan(String value) {
			addCriterion("ll_departure_phone >", value, "llDeparturePhone");
			return this;
		}

		public Criteria andLlDeparturePhoneGreaterThanOrEqualTo(String value) {
			addCriterion("ll_departure_phone >=", value, "llDeparturePhone");
			return this;
		}

		public Criteria andLlDeparturePhoneLessThan(String value) {
			addCriterion("ll_departure_phone <", value, "llDeparturePhone");
			return this;
		}

		public Criteria andLlDeparturePhoneLessThanOrEqualTo(String value) {
			addCriterion("ll_departure_phone <=", value, "llDeparturePhone");
			return this;
		}

		public Criteria andLlDeparturePhoneLike(String value) {
			addCriterion("ll_departure_phone like", value, "llDeparturePhone");
			return this;
		}

		public Criteria andLlDeparturePhoneNotLike(String value) {
			addCriterion("ll_departure_phone not like", value,
					"llDeparturePhone");
			return this;
		}

		public Criteria andLlDeparturePhoneIn(List values) {
			addCriterion("ll_departure_phone in", values, "llDeparturePhone");
			return this;
		}

		public Criteria andLlDeparturePhoneNotIn(List values) {
			addCriterion("ll_departure_phone not in", values,
					"llDeparturePhone");
			return this;
		}

		public Criteria andLlDeparturePhoneBetween(String value1, String value2) {
			addCriterion("ll_departure_phone between", value1, value2,
					"llDeparturePhone");
			return this;
		}

		public Criteria andLlDeparturePhoneNotBetween(String value1,
				String value2) {
			addCriterion("ll_departure_phone not between", value1, value2,
					"llDeparturePhone");
			return this;
		}

		public Criteria andLlDepartureLanllineIsNull() {
			addCriterion("ll_departure_lanlline is null");
			return this;
		}

		public Criteria andLlDepartureLanllineIsNotNull() {
			addCriterion("ll_departure_lanlline is not null");
			return this;
		}

		public Criteria andLlDepartureLanllineEqualTo(String value) {
			addCriterion("ll_departure_lanlline =", value,
					"llDepartureLanlline");
			return this;
		}

		public Criteria andLlDepartureLanllineNotEqualTo(String value) {
			addCriterion("ll_departure_lanlline <>", value,
					"llDepartureLanlline");
			return this;
		}

		public Criteria andLlDepartureLanllineGreaterThan(String value) {
			addCriterion("ll_departure_lanlline >", value,
					"llDepartureLanlline");
			return this;
		}

		public Criteria andLlDepartureLanllineGreaterThanOrEqualTo(String value) {
			addCriterion("ll_departure_lanlline >=", value,
					"llDepartureLanlline");
			return this;
		}

		public Criteria andLlDepartureLanllineLessThan(String value) {
			addCriterion("ll_departure_lanlline <", value,
					"llDepartureLanlline");
			return this;
		}

		public Criteria andLlDepartureLanllineLessThanOrEqualTo(String value) {
			addCriterion("ll_departure_lanlline <=", value,
					"llDepartureLanlline");
			return this;
		}

		public Criteria andLlDepartureLanllineLike(String value) {
			addCriterion("ll_departure_lanlline like", value,
					"llDepartureLanlline");
			return this;
		}

		public Criteria andLlDepartureLanllineNotLike(String value) {
			addCriterion("ll_departure_lanlline not like", value,
					"llDepartureLanlline");
			return this;
		}

		public Criteria andLlDepartureLanllineIn(List values) {
			addCriterion("ll_departure_lanlline in", values,
					"llDepartureLanlline");
			return this;
		}

		public Criteria andLlDepartureLanllineNotIn(List values) {
			addCriterion("ll_departure_lanlline not in", values,
					"llDepartureLanlline");
			return this;
		}

		public Criteria andLlDepartureLanllineBetween(String value1,
				String value2) {
			addCriterion("ll_departure_lanlline between", value1, value2,
					"llDepartureLanlline");
			return this;
		}

		public Criteria andLlDepartureLanllineNotBetween(String value1,
				String value2) {
			addCriterion("ll_departure_lanlline not between", value1, value2,
					"llDepartureLanlline");
			return this;
		}

		public Criteria andLlDestinationProvinceIsNull() {
			addCriterion("ll_destination_province is null");
			return this;
		}

		public Criteria andLlDestinationProvinceIsNotNull() {
			addCriterion("ll_destination_province is not null");
			return this;
		}

		public Criteria andLlDestinationProvinceEqualTo(String value) {
			addCriterion("ll_destination_province =", value,
					"llDestinationProvince");
			return this;
		}

		public Criteria andLlDestinationProvinceNotEqualTo(String value) {
			addCriterion("ll_destination_province <>", value,
					"llDestinationProvince");
			return this;
		}

		public Criteria andLlDestinationProvinceGreaterThan(String value) {
			addCriterion("ll_destination_province >", value,
					"llDestinationProvince");
			return this;
		}

		public Criteria andLlDestinationProvinceGreaterThanOrEqualTo(
				String value) {
			addCriterion("ll_destination_province >=", value,
					"llDestinationProvince");
			return this;
		}

		public Criteria andLlDestinationProvinceLessThan(String value) {
			addCriterion("ll_destination_province <", value,
					"llDestinationProvince");
			return this;
		}

		public Criteria andLlDestinationProvinceLessThanOrEqualTo(String value) {
			addCriterion("ll_destination_province <=", value,
					"llDestinationProvince");
			return this;
		}

		public Criteria andLlDestinationProvinceLike(String value) {
			addCriterion("ll_destination_province like", value,
					"llDestinationProvince");
			return this;
		}

		public Criteria andLlDestinationProvinceNotLike(String value) {
			addCriterion("ll_destination_province not like", value,
					"llDestinationProvince");
			return this;
		}

		public Criteria andLlDestinationProvinceIn(List values) {
			addCriterion("ll_destination_province in", values,
					"llDestinationProvince");
			return this;
		}

		public Criteria andLlDestinationProvinceNotIn(List values) {
			addCriterion("ll_destination_province not in", values,
					"llDestinationProvince");
			return this;
		}

		public Criteria andLlDestinationProvinceBetween(String value1,
				String value2) {
			addCriterion("ll_destination_province between", value1, value2,
					"llDestinationProvince");
			return this;
		}

		public Criteria andLlDestinationProvinceNotBetween(String value1,
				String value2) {
			addCriterion("ll_destination_province not between", value1, value2,
					"llDestinationProvince");
			return this;
		}

		public Criteria andLlDestinationCityIsNull() {
			addCriterion("ll_destination_city is null");
			return this;
		}

		public Criteria andLlDestinationCityIsNotNull() {
			addCriterion("ll_destination_city is not null");
			return this;
		}

		public Criteria andLlDestinationCityEqualTo(String value) {
			addCriterion("ll_destination_city =", value, "llDestinationCity");
			return this;
		}

		public Criteria andLlDestinationCityNotEqualTo(String value) {
			addCriterion("ll_destination_city <>", value, "llDestinationCity");
			return this;
		}

		public Criteria andLlDestinationCityGreaterThan(String value) {
			addCriterion("ll_destination_city >", value, "llDestinationCity");
			return this;
		}

		public Criteria andLlDestinationCityGreaterThanOrEqualTo(String value) {
			addCriterion("ll_destination_city >=", value, "llDestinationCity");
			return this;
		}

		public Criteria andLlDestinationCityLessThan(String value) {
			addCriterion("ll_destination_city <", value, "llDestinationCity");
			return this;
		}

		public Criteria andLlDestinationCityLessThanOrEqualTo(String value) {
			addCriterion("ll_destination_city <=", value, "llDestinationCity");
			return this;
		}

		public Criteria andLlDestinationCityLike(String value) {
			addCriterion("ll_destination_city like", value, "llDestinationCity");
			return this;
		}

		public Criteria andLlDestinationCityNotLike(String value) {
			addCriterion("ll_destination_city not like", value,
					"llDestinationCity");
			return this;
		}

		public Criteria andLlDestinationCityIn(List values) {
			addCriterion("ll_destination_city in", values, "llDestinationCity");
			return this;
		}

		public Criteria andLlDestinationCityNotIn(List values) {
			addCriterion("ll_destination_city not in", values,
					"llDestinationCity");
			return this;
		}

		public Criteria andLlDestinationCityBetween(String value1, String value2) {
			addCriterion("ll_destination_city between", value1, value2,
					"llDestinationCity");
			return this;
		}

		public Criteria andLlDestinationCityNotBetween(String value1,
				String value2) {
			addCriterion("ll_destination_city not between", value1, value2,
					"llDestinationCity");
			return this;
		}

		public Criteria andLlDestinationAreaIsNull() {
			addCriterion("ll_destination_area is null");
			return this;
		}

		public Criteria andLlDestinationAreaIsNotNull() {
			addCriterion("ll_destination_area is not null");
			return this;
		}

		public Criteria andLlDestinationAreaEqualTo(String value) {
			addCriterion("ll_destination_area =", value, "llDestinationArea");
			return this;
		}

		public Criteria andLlDestinationAreaNotEqualTo(String value) {
			addCriterion("ll_destination_area <>", value, "llDestinationArea");
			return this;
		}

		public Criteria andLlDestinationAreaGreaterThan(String value) {
			addCriterion("ll_destination_area >", value, "llDestinationArea");
			return this;
		}

		public Criteria andLlDestinationAreaGreaterThanOrEqualTo(String value) {
			addCriterion("ll_destination_area >=", value, "llDestinationArea");
			return this;
		}

		public Criteria andLlDestinationAreaLessThan(String value) {
			addCriterion("ll_destination_area <", value, "llDestinationArea");
			return this;
		}

		public Criteria andLlDestinationAreaLessThanOrEqualTo(String value) {
			addCriterion("ll_destination_area <=", value, "llDestinationArea");
			return this;
		}

		public Criteria andLlDestinationAreaLike(String value) {
			addCriterion("ll_destination_area like", value, "llDestinationArea");
			return this;
		}

		public Criteria andLlDestinationAreaNotLike(String value) {
			addCriterion("ll_destination_area not like", value,
					"llDestinationArea");
			return this;
		}

		public Criteria andLlDestinationAreaIn(List values) {
			addCriterion("ll_destination_area in", values, "llDestinationArea");
			return this;
		}

		public Criteria andLlDestinationAreaNotIn(List values) {
			addCriterion("ll_destination_area not in", values,
					"llDestinationArea");
			return this;
		}

		public Criteria andLlDestinationAreaBetween(String value1, String value2) {
			addCriterion("ll_destination_area between", value1, value2,
					"llDestinationArea");
			return this;
		}

		public Criteria andLlDestinationAreaNotBetween(String value1,
				String value2) {
			addCriterion("ll_destination_area not between", value1, value2,
					"llDestinationArea");
			return this;
		}

		public Criteria andLlDestinationNetworkIsNull() {
			addCriterion("ll_destination_network is null");
			return this;
		}

		public Criteria andLlDestinationNetworkIsNotNull() {
			addCriterion("ll_destination_network is not null");
			return this;
		}

		public Criteria andLlDestinationNetworkEqualTo(String value) {
			addCriterion("ll_destination_network =", value,
					"llDestinationNetwork");
			return this;
		}

		public Criteria andLlDestinationNetworkNotEqualTo(String value) {
			addCriterion("ll_destination_network <>", value,
					"llDestinationNetwork");
			return this;
		}

		public Criteria andLlDestinationNetworkGreaterThan(String value) {
			addCriterion("ll_destination_network >", value,
					"llDestinationNetwork");
			return this;
		}

		public Criteria andLlDestinationNetworkGreaterThanOrEqualTo(String value) {
			addCriterion("ll_destination_network >=", value,
					"llDestinationNetwork");
			return this;
		}

		public Criteria andLlDestinationNetworkLessThan(String value) {
			addCriterion("ll_destination_network <", value,
					"llDestinationNetwork");
			return this;
		}

		public Criteria andLlDestinationNetworkLessThanOrEqualTo(String value) {
			addCriterion("ll_destination_network <=", value,
					"llDestinationNetwork");
			return this;
		}

		public Criteria andLlDestinationNetworkLike(String value) {
			addCriterion("ll_destination_network like", value,
					"llDestinationNetwork");
			return this;
		}

		public Criteria andLlDestinationNetworkNotLike(String value) {
			addCriterion("ll_destination_network not like", value,
					"llDestinationNetwork");
			return this;
		}

		public Criteria andLlDestinationNetworkIn(List values) {
			addCriterion("ll_destination_network in", values,
					"llDestinationNetwork");
			return this;
		}

		public Criteria andLlDestinationNetworkNotIn(List values) {
			addCriterion("ll_destination_network not in", values,
					"llDestinationNetwork");
			return this;
		}

		public Criteria andLlDestinationNetworkBetween(String value1,
				String value2) {
			addCriterion("ll_destination_network between", value1, value2,
					"llDestinationNetwork");
			return this;
		}

		public Criteria andLlDestinationNetworkNotBetween(String value1,
				String value2) {
			addCriterion("ll_destination_network not between", value1, value2,
					"llDestinationNetwork");
			return this;
		}

		public Criteria andLlDestinationAddressIsNull() {
			addCriterion("ll_destination_address is null");
			return this;
		}

		public Criteria andLlDestinationAddressIsNotNull() {
			addCriterion("ll_destination_address is not null");
			return this;
		}

		public Criteria andLlDestinationAddressEqualTo(String value) {
			addCriterion("ll_destination_address =", value,
					"llDestinationAddress");
			return this;
		}

		public Criteria andLlDestinationAddressNotEqualTo(String value) {
			addCriterion("ll_destination_address <>", value,
					"llDestinationAddress");
			return this;
		}

		public Criteria andLlDestinationAddressGreaterThan(String value) {
			addCriterion("ll_destination_address >", value,
					"llDestinationAddress");
			return this;
		}

		public Criteria andLlDestinationAddressGreaterThanOrEqualTo(String value) {
			addCriterion("ll_destination_address >=", value,
					"llDestinationAddress");
			return this;
		}

		public Criteria andLlDestinationAddressLessThan(String value) {
			addCriterion("ll_destination_address <", value,
					"llDestinationAddress");
			return this;
		}

		public Criteria andLlDestinationAddressLessThanOrEqualTo(String value) {
			addCriterion("ll_destination_address <=", value,
					"llDestinationAddress");
			return this;
		}

		public Criteria andLlDestinationAddressLike(String value) {
			addCriterion("ll_destination_address like", value,
					"llDestinationAddress");
			return this;
		}

		public Criteria andLlDestinationAddressNotLike(String value) {
			addCriterion("ll_destination_address not like", value,
					"llDestinationAddress");
			return this;
		}

		public Criteria andLlDestinationAddressIn(List values) {
			addCriterion("ll_destination_address in", values,
					"llDestinationAddress");
			return this;
		}

		public Criteria andLlDestinationAddressNotIn(List values) {
			addCriterion("ll_destination_address not in", values,
					"llDestinationAddress");
			return this;
		}

		public Criteria andLlDestinationAddressBetween(String value1,
				String value2) {
			addCriterion("ll_destination_address between", value1, value2,
					"llDestinationAddress");
			return this;
		}

		public Criteria andLlDestinationAddressNotBetween(String value1,
				String value2) {
			addCriterion("ll_destination_address not between", value1, value2,
					"llDestinationAddress");
			return this;
		}

		public Criteria andLlDestinationPersonNameIsNull() {
			addCriterion("ll_destination_person_name is null");
			return this;
		}

		public Criteria andLlDestinationPersonNameIsNotNull() {
			addCriterion("ll_destination_person_name is not null");
			return this;
		}

		public Criteria andLlDestinationPersonNameEqualTo(String value) {
			addCriterion("ll_destination_person_name =", value,
					"llDestinationPersonName");
			return this;
		}

		public Criteria andLlDestinationPersonNameNotEqualTo(String value) {
			addCriterion("ll_destination_person_name <>", value,
					"llDestinationPersonName");
			return this;
		}

		public Criteria andLlDestinationPersonNameGreaterThan(String value) {
			addCriterion("ll_destination_person_name >", value,
					"llDestinationPersonName");
			return this;
		}

		public Criteria andLlDestinationPersonNameGreaterThanOrEqualTo(
				String value) {
			addCriterion("ll_destination_person_name >=", value,
					"llDestinationPersonName");
			return this;
		}

		public Criteria andLlDestinationPersonNameLessThan(String value) {
			addCriterion("ll_destination_person_name <", value,
					"llDestinationPersonName");
			return this;
		}

		public Criteria andLlDestinationPersonNameLessThanOrEqualTo(String value) {
			addCriterion("ll_destination_person_name <=", value,
					"llDestinationPersonName");
			return this;
		}

		public Criteria andLlDestinationPersonNameLike(String value) {
			addCriterion("ll_destination_person_name like", value,
					"llDestinationPersonName");
			return this;
		}

		public Criteria andLlDestinationPersonNameNotLike(String value) {
			addCriterion("ll_destination_person_name not like", value,
					"llDestinationPersonName");
			return this;
		}

		public Criteria andLlDestinationPersonNameIn(List values) {
			addCriterion("ll_destination_person_name in", values,
					"llDestinationPersonName");
			return this;
		}

		public Criteria andLlDestinationPersonNameNotIn(List values) {
			addCriterion("ll_destination_person_name not in", values,
					"llDestinationPersonName");
			return this;
		}

		public Criteria andLlDestinationPersonNameBetween(String value1,
				String value2) {
			addCriterion("ll_destination_person_name between", value1, value2,
					"llDestinationPersonName");
			return this;
		}

		public Criteria andLlDestinationPersonNameNotBetween(String value1,
				String value2) {
			addCriterion("ll_destination_person_name not between", value1,
					value2, "llDestinationPersonName");
			return this;
		}

		public Criteria andLlDestinationPhoneIsNull() {
			addCriterion("ll_destination_phone is null");
			return this;
		}

		public Criteria andLlDestinationPhoneIsNotNull() {
			addCriterion("ll_destination_phone is not null");
			return this;
		}

		public Criteria andLlDestinationPhoneEqualTo(String value) {
			addCriterion("ll_destination_phone =", value, "llDestinationPhone");
			return this;
		}

		public Criteria andLlDestinationPhoneNotEqualTo(String value) {
			addCriterion("ll_destination_phone <>", value, "llDestinationPhone");
			return this;
		}

		public Criteria andLlDestinationPhoneGreaterThan(String value) {
			addCriterion("ll_destination_phone >", value, "llDestinationPhone");
			return this;
		}

		public Criteria andLlDestinationPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("ll_destination_phone >=", value, "llDestinationPhone");
			return this;
		}

		public Criteria andLlDestinationPhoneLessThan(String value) {
			addCriterion("ll_destination_phone <", value, "llDestinationPhone");
			return this;
		}

		public Criteria andLlDestinationPhoneLessThanOrEqualTo(String value) {
			addCriterion("ll_destination_phone <=", value, "llDestinationPhone");
			return this;
		}

		public Criteria andLlDestinationPhoneLike(String value) {
			addCriterion("ll_destination_phone like", value,
					"llDestinationPhone");
			return this;
		}

		public Criteria andLlDestinationPhoneNotLike(String value) {
			addCriterion("ll_destination_phone not like", value,
					"llDestinationPhone");
			return this;
		}

		public Criteria andLlDestinationPhoneIn(List values) {
			addCriterion("ll_destination_phone in", values,
					"llDestinationPhone");
			return this;
		}

		public Criteria andLlDestinationPhoneNotIn(List values) {
			addCriterion("ll_destination_phone not in", values,
					"llDestinationPhone");
			return this;
		}

		public Criteria andLlDestinationPhoneBetween(String value1,
				String value2) {
			addCriterion("ll_destination_phone between", value1, value2,
					"llDestinationPhone");
			return this;
		}

		public Criteria andLlDestinationPhoneNotBetween(String value1,
				String value2) {
			addCriterion("ll_destination_phone not between", value1, value2,
					"llDestinationPhone");
			return this;
		}

		public Criteria andLlDestinationLanllineIsNull() {
			addCriterion("ll_destination_lanlline is null");
			return this;
		}

		public Criteria andLlDestinationLanllineIsNotNull() {
			addCriterion("ll_destination_lanlline is not null");
			return this;
		}

		public Criteria andLlDestinationLanllineEqualTo(String value) {
			addCriterion("ll_destination_lanlline =", value,
					"llDestinationLanlline");
			return this;
		}

		public Criteria andLlDestinationLanllineNotEqualTo(String value) {
			addCriterion("ll_destination_lanlline <>", value,
					"llDestinationLanlline");
			return this;
		}

		public Criteria andLlDestinationLanllineGreaterThan(String value) {
			addCriterion("ll_destination_lanlline >", value,
					"llDestinationLanlline");
			return this;
		}

		public Criteria andLlDestinationLanllineGreaterThanOrEqualTo(
				String value) {
			addCriterion("ll_destination_lanlline >=", value,
					"llDestinationLanlline");
			return this;
		}

		public Criteria andLlDestinationLanllineLessThan(String value) {
			addCriterion("ll_destination_lanlline <", value,
					"llDestinationLanlline");
			return this;
		}

		public Criteria andLlDestinationLanllineLessThanOrEqualTo(String value) {
			addCriterion("ll_destination_lanlline <=", value,
					"llDestinationLanlline");
			return this;
		}

		public Criteria andLlDestinationLanllineLike(String value) {
			addCriterion("ll_destination_lanlline like", value,
					"llDestinationLanlline");
			return this;
		}

		public Criteria andLlDestinationLanllineNotLike(String value) {
			addCriterion("ll_destination_lanlline not like", value,
					"llDestinationLanlline");
			return this;
		}

		public Criteria andLlDestinationLanllineIn(List values) {
			addCriterion("ll_destination_lanlline in", values,
					"llDestinationLanlline");
			return this;
		}

		public Criteria andLlDestinationLanllineNotIn(List values) {
			addCriterion("ll_destination_lanlline not in", values,
					"llDestinationLanlline");
			return this;
		}

		public Criteria andLlDestinationLanllineBetween(String value1,
				String value2) {
			addCriterion("ll_destination_lanlline between", value1, value2,
					"llDestinationLanlline");
			return this;
		}

		public Criteria andLlDestinationLanllineNotBetween(String value1,
				String value2) {
			addCriterion("ll_destination_lanlline not between", value1, value2,
					"llDestinationLanlline");
			return this;
		}

		public Criteria andLlHeavyCargoIsNull() {
			addCriterion("ll_heavy_cargo is null");
			return this;
		}

		public Criteria andLlHeavyCargoIsNotNull() {
			addCriterion("ll_heavy_cargo is not null");
			return this;
		}

		public Criteria andLlHeavyCargoEqualTo(BigDecimal value) {
			addCriterion("ll_heavy_cargo =", value, "llHeavyCargo");
			return this;
		}

		public Criteria andLlHeavyCargoNotEqualTo(BigDecimal value) {
			addCriterion("ll_heavy_cargo <>", value, "llHeavyCargo");
			return this;
		}

		public Criteria andLlHeavyCargoGreaterThan(BigDecimal value) {
			addCriterion("ll_heavy_cargo >", value, "llHeavyCargo");
			return this;
		}

		public Criteria andLlHeavyCargoGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("ll_heavy_cargo >=", value, "llHeavyCargo");
			return this;
		}

		public Criteria andLlHeavyCargoLessThan(BigDecimal value) {
			addCriterion("ll_heavy_cargo <", value, "llHeavyCargo");
			return this;
		}

		public Criteria andLlHeavyCargoLessThanOrEqualTo(BigDecimal value) {
			addCriterion("ll_heavy_cargo <=", value, "llHeavyCargo");
			return this;
		}

		public Criteria andLlHeavyCargoIn(List values) {
			addCriterion("ll_heavy_cargo in", values, "llHeavyCargo");
			return this;
		}

		public Criteria andLlHeavyCargoNotIn(List values) {
			addCriterion("ll_heavy_cargo not in", values, "llHeavyCargo");
			return this;
		}

		public Criteria andLlHeavyCargoBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("ll_heavy_cargo between", value1, value2,
					"llHeavyCargo");
			return this;
		}

		public Criteria andLlHeavyCargoNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("ll_heavy_cargo not between", value1, value2,
					"llHeavyCargo");
			return this;
		}

		public Criteria andLlLightCargoIsNull() {
			addCriterion("ll_light_cargo is null");
			return this;
		}

		public Criteria andLlLightCargoIsNotNull() {
			addCriterion("ll_light_cargo is not null");
			return this;
		}

		public Criteria andLlLightCargoEqualTo(BigDecimal value) {
			addCriterion("ll_light_cargo =", value, "llLightCargo");
			return this;
		}

		public Criteria andLlLightCargoNotEqualTo(BigDecimal value) {
			addCriterion("ll_light_cargo <>", value, "llLightCargo");
			return this;
		}

		public Criteria andLlLightCargoGreaterThan(BigDecimal value) {
			addCriterion("ll_light_cargo >", value, "llLightCargo");
			return this;
		}

		public Criteria andLlLightCargoGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("ll_light_cargo >=", value, "llLightCargo");
			return this;
		}

		public Criteria andLlLightCargoLessThan(BigDecimal value) {
			addCriterion("ll_light_cargo <", value, "llLightCargo");
			return this;
		}

		public Criteria andLlLightCargoLessThanOrEqualTo(BigDecimal value) {
			addCriterion("ll_light_cargo <=", value, "llLightCargo");
			return this;
		}

		public Criteria andLlLightCargoIn(List values) {
			addCriterion("ll_light_cargo in", values, "llLightCargo");
			return this;
		}

		public Criteria andLlLightCargoNotIn(List values) {
			addCriterion("ll_light_cargo not in", values, "llLightCargo");
			return this;
		}

		public Criteria andLlLightCargoBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("ll_light_cargo between", value1, value2,
					"llLightCargo");
			return this;
		}

		public Criteria andLlLightCargoNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("ll_light_cargo not between", value1, value2,
					"llLightCargo");
			return this;
		}

		public Criteria andLlMinimumIsNull() {
			addCriterion("ll_minimum is null");
			return this;
		}

		public Criteria andLlMinimumIsNotNull() {
			addCriterion("ll_minimum is not null");
			return this;
		}

		public Criteria andLlMinimumEqualTo(BigDecimal value) {
			addCriterion("ll_minimum =", value, "llMinimum");
			return this;
		}

		public Criteria andLlMinimumNotEqualTo(BigDecimal value) {
			addCriterion("ll_minimum <>", value, "llMinimum");
			return this;
		}

		public Criteria andLlMinimumGreaterThan(BigDecimal value) {
			addCriterion("ll_minimum >", value, "llMinimum");
			return this;
		}

		public Criteria andLlMinimumGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("ll_minimum >=", value, "llMinimum");
			return this;
		}

		public Criteria andLlMinimumLessThan(BigDecimal value) {
			addCriterion("ll_minimum <", value, "llMinimum");
			return this;
		}

		public Criteria andLlMinimumLessThanOrEqualTo(BigDecimal value) {
			addCriterion("ll_minimum <=", value, "llMinimum");
			return this;
		}

		public Criteria andLlMinimumIn(List values) {
			addCriterion("ll_minimum in", values, "llMinimum");
			return this;
		}

		public Criteria andLlMinimumNotIn(List values) {
			addCriterion("ll_minimum not in", values, "llMinimum");
			return this;
		}

		public Criteria andLlMinimumBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("ll_minimum between", value1, value2, "llMinimum");
			return this;
		}

		public Criteria andLlMinimumNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("ll_minimum not between", value1, value2, "llMinimum");
			return this;
		}

		public Criteria andLlPrescriptionIsNull() {
			addCriterion("ll_prescription is null");
			return this;
		}

		public Criteria andLlPrescriptionIsNotNull() {
			addCriterion("ll_prescription is not null");
			return this;
		}

		public Criteria andLlPrescriptionEqualTo(String value) {
			addCriterion("ll_prescription =", value, "llPrescription");
			return this;
		}

		public Criteria andLlPrescriptionNotEqualTo(String value) {
			addCriterion("ll_prescription <>", value, "llPrescription");
			return this;
		}

		public Criteria andLlPrescriptionGreaterThan(String value) {
			addCriterion("ll_prescription >", value, "llPrescription");
			return this;
		}

		public Criteria andLlPrescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("ll_prescription >=", value, "llPrescription");
			return this;
		}

		public Criteria andLlPrescriptionLessThan(String value) {
			addCriterion("ll_prescription <", value, "llPrescription");
			return this;
		}

		public Criteria andLlPrescriptionLessThanOrEqualTo(String value) {
			addCriterion("ll_prescription <=", value, "llPrescription");
			return this;
		}

		public Criteria andLlPrescriptionLike(String value) {
			addCriterion("ll_prescription like", value, "llPrescription");
			return this;
		}

		public Criteria andLlPrescriptionNotLike(String value) {
			addCriterion("ll_prescription not like", value, "llPrescription");
			return this;
		}

		public Criteria andLlPrescriptionIn(List values) {
			addCriterion("ll_prescription in", values, "llPrescription");
			return this;
		}

		public Criteria andLlPrescriptionNotIn(List values) {
			addCriterion("ll_prescription not in", values, "llPrescription");
			return this;
		}

		public Criteria andLlPrescriptionBetween(String value1, String value2) {
			addCriterion("ll_prescription between", value1, value2,
					"llPrescription");
			return this;
		}

		public Criteria andLlPrescriptionNotBetween(String value1, String value2) {
			addCriterion("ll_prescription not between", value1, value2,
					"llPrescription");
			return this;
		}

		public Criteria andLlPrescriptionUnitsIsNull() {
			addCriterion("ll_prescription_units is null");
			return this;
		}

		public Criteria andLlPrescriptionUnitsIsNotNull() {
			addCriterion("ll_prescription_units is not null");
			return this;
		}

		public Criteria andLlPrescriptionUnitsEqualTo(String value) {
			addCriterion("ll_prescription_units =", value,
					"llPrescriptionUnits");
			return this;
		}

		public Criteria andLlPrescriptionUnitsNotEqualTo(String value) {
			addCriterion("ll_prescription_units <>", value,
					"llPrescriptionUnits");
			return this;
		}

		public Criteria andLlPrescriptionUnitsGreaterThan(String value) {
			addCriterion("ll_prescription_units >", value,
					"llPrescriptionUnits");
			return this;
		}

		public Criteria andLlPrescriptionUnitsGreaterThanOrEqualTo(String value) {
			addCriterion("ll_prescription_units >=", value,
					"llPrescriptionUnits");
			return this;
		}

		public Criteria andLlPrescriptionUnitsLessThan(String value) {
			addCriterion("ll_prescription_units <", value,
					"llPrescriptionUnits");
			return this;
		}

		public Criteria andLlPrescriptionUnitsLessThanOrEqualTo(String value) {
			addCriterion("ll_prescription_units <=", value,
					"llPrescriptionUnits");
			return this;
		}

		public Criteria andLlPrescriptionUnitsLike(String value) {
			addCriterion("ll_prescription_units like", value,
					"llPrescriptionUnits");
			return this;
		}

		public Criteria andLlPrescriptionUnitsNotLike(String value) {
			addCriterion("ll_prescription_units not like", value,
					"llPrescriptionUnits");
			return this;
		}

		public Criteria andLlPrescriptionUnitsIn(List values) {
			addCriterion("ll_prescription_units in", values,
					"llPrescriptionUnits");
			return this;
		}

		public Criteria andLlPrescriptionUnitsNotIn(List values) {
			addCriterion("ll_prescription_units not in", values,
					"llPrescriptionUnits");
			return this;
		}

		public Criteria andLlPrescriptionUnitsBetween(String value1,
				String value2) {
			addCriterion("ll_prescription_units between", value1, value2,
					"llPrescriptionUnits");
			return this;
		}

		public Criteria andLlPrescriptionUnitsNotBetween(String value1,
				String value2) {
			addCriterion("ll_prescription_units not between", value1, value2,
					"llPrescriptionUnits");
			return this;
		}

		public Criteria andLlFrequencyIsNull() {
			addCriterion("ll_frequency is null");
			return this;
		}

		public Criteria andLlFrequencyIsNotNull() {
			addCriterion("ll_frequency is not null");
			return this;
		}

		public Criteria andLlFrequencyEqualTo(String value) {
			addCriterion("ll_frequency =", value, "llFrequency");
			return this;
		}

		public Criteria andLlFrequencyNotEqualTo(String value) {
			addCriterion("ll_frequency <>", value, "llFrequency");
			return this;
		}

		public Criteria andLlFrequencyGreaterThan(String value) {
			addCriterion("ll_frequency >", value, "llFrequency");
			return this;
		}

		public Criteria andLlFrequencyGreaterThanOrEqualTo(String value) {
			addCriterion("ll_frequency >=", value, "llFrequency");
			return this;
		}

		public Criteria andLlFrequencyLessThan(String value) {
			addCriterion("ll_frequency <", value, "llFrequency");
			return this;
		}

		public Criteria andLlFrequencyLessThanOrEqualTo(String value) {
			addCriterion("ll_frequency <=", value, "llFrequency");
			return this;
		}

		public Criteria andLlFrequencyLike(String value) {
			addCriterion("ll_frequency like", value, "llFrequency");
			return this;
		}

		public Criteria andLlFrequencyNotLike(String value) {
			addCriterion("ll_frequency not like", value, "llFrequency");
			return this;
		}

		public Criteria andLlFrequencyIn(List values) {
			addCriterion("ll_frequency in", values, "llFrequency");
			return this;
		}

		public Criteria andLlFrequencyNotIn(List values) {
			addCriterion("ll_frequency not in", values, "llFrequency");
			return this;
		}

		public Criteria andLlFrequencyBetween(String value1, String value2) {
			addCriterion("ll_frequency between", value1, value2, "llFrequency");
			return this;
		}

		public Criteria andLlFrequencyNotBetween(String value1, String value2) {
			addCriterion("ll_frequency not between", value1, value2,
					"llFrequency");
			return this;
		}

		public Criteria andLlFrequencyUnitsIsNull() {
			addCriterion("ll_frequency_units is null");
			return this;
		}

		public Criteria andLlFrequencyUnitsIsNotNull() {
			addCriterion("ll_frequency_units is not null");
			return this;
		}

		public Criteria andLlFrequencyUnitsEqualTo(String value) {
			addCriterion("ll_frequency_units =", value, "llFrequencyUnits");
			return this;
		}

		public Criteria andLlFrequencyUnitsNotEqualTo(String value) {
			addCriterion("ll_frequency_units <>", value, "llFrequencyUnits");
			return this;
		}

		public Criteria andLlFrequencyUnitsGreaterThan(String value) {
			addCriterion("ll_frequency_units >", value, "llFrequencyUnits");
			return this;
		}

		public Criteria andLlFrequencyUnitsGreaterThanOrEqualTo(String value) {
			addCriterion("ll_frequency_units >=", value, "llFrequencyUnits");
			return this;
		}

		public Criteria andLlFrequencyUnitsLessThan(String value) {
			addCriterion("ll_frequency_units <", value, "llFrequencyUnits");
			return this;
		}

		public Criteria andLlFrequencyUnitsLessThanOrEqualTo(String value) {
			addCriterion("ll_frequency_units <=", value, "llFrequencyUnits");
			return this;
		}

		public Criteria andLlFrequencyUnitsLike(String value) {
			addCriterion("ll_frequency_units like", value, "llFrequencyUnits");
			return this;
		}

		public Criteria andLlFrequencyUnitsNotLike(String value) {
			addCriterion("ll_frequency_units not like", value,
					"llFrequencyUnits");
			return this;
		}

		public Criteria andLlFrequencyUnitsIn(List values) {
			addCriterion("ll_frequency_units in", values, "llFrequencyUnits");
			return this;
		}

		public Criteria andLlFrequencyUnitsNotIn(List values) {
			addCriterion("ll_frequency_units not in", values,
					"llFrequencyUnits");
			return this;
		}

		public Criteria andLlFrequencyUnitsBetween(String value1, String value2) {
			addCriterion("ll_frequency_units between", value1, value2,
					"llFrequencyUnits");
			return this;
		}

		public Criteria andLlFrequencyUnitsNotBetween(String value1,
				String value2) {
			addCriterion("ll_frequency_units not between", value1, value2,
					"llFrequencyUnits");
			return this;
		}

		public Criteria andLlCarSpecIsNull() {
			addCriterion("ll_car_spec is null");
			return this;
		}

		public Criteria andLlCarSpecIsNotNull() {
			addCriterion("ll_car_spec is not null");
			return this;
		}

		public Criteria andLlCarSpecEqualTo(String value) {
			addCriterion("ll_car_spec =", value, "llCarSpec");
			return this;
		}

		public Criteria andLlCarSpecNotEqualTo(String value) {
			addCriterion("ll_car_spec <>", value, "llCarSpec");
			return this;
		}

		public Criteria andLlCarSpecGreaterThan(String value) {
			addCriterion("ll_car_spec >", value, "llCarSpec");
			return this;
		}

		public Criteria andLlCarSpecGreaterThanOrEqualTo(String value) {
			addCriterion("ll_car_spec >=", value, "llCarSpec");
			return this;
		}

		public Criteria andLlCarSpecLessThan(String value) {
			addCriterion("ll_car_spec <", value, "llCarSpec");
			return this;
		}

		public Criteria andLlCarSpecLessThanOrEqualTo(String value) {
			addCriterion("ll_car_spec <=", value, "llCarSpec");
			return this;
		}

		public Criteria andLlCarSpecLike(String value) {
			addCriterion("ll_car_spec like", value, "llCarSpec");
			return this;
		}

		public Criteria andLlCarSpecNotLike(String value) {
			addCriterion("ll_car_spec not like", value, "llCarSpec");
			return this;
		}

		public Criteria andLlCarSpecIn(List values) {
			addCriterion("ll_car_spec in", values, "llCarSpec");
			return this;
		}

		public Criteria andLlCarSpecNotIn(List values) {
			addCriterion("ll_car_spec not in", values, "llCarSpec");
			return this;
		}

		public Criteria andLlCarSpecBetween(String value1, String value2) {
			addCriterion("ll_car_spec between", value1, value2, "llCarSpec");
			return this;
		}

		public Criteria andLlCarSpecNotBetween(String value1, String value2) {
			addCriterion("ll_car_spec not between", value1, value2, "llCarSpec");
			return this;
		}

		public Criteria andLlStatusIsNull() {
			addCriterion("ll_status is null");
			return this;
		}

		public Criteria andLlStatusIsNotNull() {
			addCriterion("ll_status is not null");
			return this;
		}

		public Criteria andLlStatusEqualTo(String value) {
			addCriterion("ll_status =", value, "llStatus");
			return this;
		}

		public Criteria andLlStatusNotEqualTo(String value) {
			addCriterion("ll_status <>", value, "llStatus");
			return this;
		}

		public Criteria andLlStatusGreaterThan(String value) {
			addCriterion("ll_status >", value, "llStatus");
			return this;
		}

		public Criteria andLlStatusGreaterThanOrEqualTo(String value) {
			addCriterion("ll_status >=", value, "llStatus");
			return this;
		}

		public Criteria andLlStatusLessThan(String value) {
			addCriterion("ll_status <", value, "llStatus");
			return this;
		}

		public Criteria andLlStatusLessThanOrEqualTo(String value) {
			addCriterion("ll_status <=", value, "llStatus");
			return this;
		}

		public Criteria andLlStatusLike(String value) {
			addCriterion("ll_status like", value, "llStatus");
			return this;
		}

		public Criteria andLlStatusNotLike(String value) {
			addCriterion("ll_status not like", value, "llStatus");
			return this;
		}

		public Criteria andLlStatusIn(List values) {
			addCriterion("ll_status in", values, "llStatus");
			return this;
		}

		public Criteria andLlStatusNotIn(List values) {
			addCriterion("ll_status not in", values, "llStatus");
			return this;
		}

		public Criteria andLlStatusBetween(String value1, String value2) {
			addCriterion("ll_status between", value1, value2, "llStatus");
			return this;
		}

		public Criteria andLlStatusNotBetween(String value1, String value2) {
			addCriterion("ll_status not between", value1, value2, "llStatus");
			return this;
		}

		public Criteria andLlDescriptionsIsNull() {
			addCriterion("ll_descriptions is null");
			return this;
		}

		public Criteria andLlDescriptionsIsNotNull() {
			addCriterion("ll_descriptions is not null");
			return this;
		}

		public Criteria andLlDescriptionsEqualTo(String value) {
			addCriterion("ll_descriptions =", value, "llDescriptions");
			return this;
		}

		public Criteria andLlDescriptionsNotEqualTo(String value) {
			addCriterion("ll_descriptions <>", value, "llDescriptions");
			return this;
		}

		public Criteria andLlDescriptionsGreaterThan(String value) {
			addCriterion("ll_descriptions >", value, "llDescriptions");
			return this;
		}

		public Criteria andLlDescriptionsGreaterThanOrEqualTo(String value) {
			addCriterion("ll_descriptions >=", value, "llDescriptions");
			return this;
		}

		public Criteria andLlDescriptionsLessThan(String value) {
			addCriterion("ll_descriptions <", value, "llDescriptions");
			return this;
		}

		public Criteria andLlDescriptionsLessThanOrEqualTo(String value) {
			addCriterion("ll_descriptions <=", value, "llDescriptions");
			return this;
		}

		public Criteria andLlDescriptionsLike(String value) {
			addCriterion("ll_descriptions like", value, "llDescriptions");
			return this;
		}

		public Criteria andLlDescriptionsNotLike(String value) {
			addCriterion("ll_descriptions not like", value, "llDescriptions");
			return this;
		}

		public Criteria andLlDescriptionsIn(List values) {
			addCriterion("ll_descriptions in", values, "llDescriptions");
			return this;
		}

		public Criteria andLlDescriptionsNotIn(List values) {
			addCriterion("ll_descriptions not in", values, "llDescriptions");
			return this;
		}

		public Criteria andLlDescriptionsBetween(String value1, String value2) {
			addCriterion("ll_descriptions between", value1, value2,
					"llDescriptions");
			return this;
		}

		public Criteria andLlDescriptionsNotBetween(String value1, String value2) {
			addCriterion("ll_descriptions not between", value1, value2,
					"llDescriptions");
			return this;
		}

		public Criteria andLlCreateTimeIsNull() {
			addCriterion("ll_create_time is null");
			return this;
		}

		public Criteria andLlCreateTimeIsNotNull() {
			addCriterion("ll_create_time is not null");
			return this;
		}

		public Criteria andLlCreateTimeEqualTo(String value) {
			addCriterion("ll_create_time =", value, "llCreateTime");
			return this;
		}

		public Criteria andLlCreateTimeNotEqualTo(String value) {
			addCriterion("ll_create_time <>", value, "llCreateTime");
			return this;
		}

		public Criteria andLlCreateTimeGreaterThan(String value) {
			addCriterion("ll_create_time >", value, "llCreateTime");
			return this;
		}

		public Criteria andLlCreateTimeGreaterThanOrEqualTo(String value) {
			addCriterion("ll_create_time >=", value, "llCreateTime");
			return this;
		}

		public Criteria andLlCreateTimeLessThan(String value) {
			addCriterion("ll_create_time <", value, "llCreateTime");
			return this;
		}

		public Criteria andLlCreateTimeLessThanOrEqualTo(String value) {
			addCriterion("ll_create_time <=", value, "llCreateTime");
			return this;
		}

		public Criteria andLlCreateTimeIn(List values) {
			addCriterion("ll_create_time in", values, "llCreateTime");
			return this;
		}

		public Criteria andLlCreateTimeNotIn(List values) {
			addCriterion("ll_create_time not in", values, "llCreateTime");
			return this;
		}

		public Criteria andLlCreateTimeBetween(String value1, String value2) {
			addCriterion("ll_create_time between", value1, value2,
					"llCreateTime");
			return this;
		}

		public Criteria andLlCreateTimeNotBetween(String value1, String value2) {
			addCriterion("ll_create_time not between", value1, value2,
					"llCreateTime");
			return this;
		}

		public Criteria andLlUpdateTimeIsNull() {
			addCriterion("ll_update_time is null");
			return this;
		}

		public Criteria andLlUpdateTimeIsNotNull() {
			addCriterion("ll_update_time is not null");
			return this;
		}

		public Criteria andLlUpdateTimeEqualTo(String value) {
			addCriterion("ll_update_time =", value, "llUpdateTime");
			return this;
		}

		public Criteria andLlUpdateTimeNotEqualTo(String value) {
			addCriterion("ll_update_time <>", value, "llUpdateTime");
			return this;
		}

		public Criteria andLlUpdateTimeGreaterThan(String value) {
			addCriterion("ll_update_time >", value, "llUpdateTime");
			return this;
		}

		public Criteria andLlUpdateTimeGreaterThanOrEqualTo(String value) {
			addCriterion("ll_update_time >=", value, "llUpdateTime");
			return this;
		}

		public Criteria andLlUpdateTimeLessThan(String value) {
			addCriterion("ll_update_time <", value, "llUpdateTime");
			return this;
		}

		public Criteria andLlUpdateTimeLessThanOrEqualTo(String value) {
			addCriterion("ll_update_time <=", value, "llUpdateTime");
			return this;
		}

		public Criteria andLlUpdateTimeIn(List values) {
			addCriterion("ll_update_time in", values, "llUpdateTime");
			return this;
		}

		public Criteria andLlUpdateTimeNotIn(List values) {
			addCriterion("ll_update_time not in", values, "llUpdateTime");
			return this;
		}

		public Criteria andLlUpdateTimeBetween(String value1, String value2) {
			addCriterion("ll_update_time between", value1, value2,
					"llUpdateTime");
			return this;
		}

		public Criteria andLlUpdateTimeNotBetween(String value1, String value2) {
			addCriterion("ll_update_time not between", value1, value2,
					"llUpdateTime");
			return this;
		}

		public Criteria andLlYnIsNull() {
			addCriterion("ll_yn is null");
			return this;
		}

		public Criteria andLlYnIsNotNull() {
			addCriterion("ll_yn is not null");
			return this;
		}

		public Criteria andLlYnEqualTo(String value) {
			addCriterion("ll_yn =", value, "llYn");
			return this;
		}

		public Criteria andLlYnNotEqualTo(String value) {
			addCriterion("ll_yn <>", value, "llYn");
			return this;
		}

		public Criteria andLlYnGreaterThan(String value) {
			addCriterion("ll_yn >", value, "llYn");
			return this;
		}

		public Criteria andLlYnGreaterThanOrEqualTo(String value) {
			addCriterion("ll_yn >=", value, "llYn");
			return this;
		}

		public Criteria andLlYnLessThan(String value) {
			addCriterion("ll_yn <", value, "llYn");
			return this;
		}

		public Criteria andLlYnLessThanOrEqualTo(String value) {
			addCriterion("ll_yn <=", value, "llYn");
			return this;
		}

		public Criteria andLlYnLike(String value) {
			addCriterion("ll_yn like", value, "llYn");
			return this;
		}

		public Criteria andLlYnNotLike(String value) {
			addCriterion("ll_yn not like", value, "llYn");
			return this;
		}

		public Criteria andLlYnIn(List values) {
			addCriterion("ll_yn in", values, "llYn");
			return this;
		}

		public Criteria andLlYnNotIn(List values) {
			addCriterion("ll_yn not in", values, "llYn");
			return this;
		}

		public Criteria andLlYnBetween(String value1, String value2) {
			addCriterion("ll_yn between", value1, value2, "llYn");
			return this;
		}

		public Criteria andLlYnNotBetween(String value1, String value2) {
			addCriterion("ll_yn not between", value1, value2, "llYn");
			return this;
		}
	}
}