package com.ada.wuliu.shipper.front.domian;

import java.math.BigDecimal;

public class LineLogistic {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_id
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private Long llId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ms_id
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private Long msId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_type
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_departure_province
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llDepartureProvince;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_departure_city
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llDepartureCity;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_departure_area
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llDepartureArea;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_departure_network
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llDepartureNetwork;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_departure_address
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llDepartureAddress;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_departure_person_name
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llDeparturePersonName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_departure_phone
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llDeparturePhone;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_departure_lanlline
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llDepartureLanlline;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_destination_province
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llDestinationProvince;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_destination_city
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llDestinationCity;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_destination_area
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llDestinationArea;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_destination_network
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llDestinationNetwork;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_destination_address
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llDestinationAddress;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_destination_person_name
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llDestinationPersonName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_destination_phone
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llDestinationPhone;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_destination_lanlline
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llDestinationLanlline;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_heavy_cargo
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private BigDecimal llHeavyCargo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_light_cargo
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private BigDecimal llLightCargo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_minimum
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private BigDecimal llMinimum;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_prescription
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llPrescription;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_prescription_units
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llPrescriptionUnits;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_frequency
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llFrequency;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_frequency_units
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llFrequencyUnits;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_car_spec
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llCarSpec;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_status
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llStatus;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_descriptions
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llDescriptions;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_create_time
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llCreateTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_update_time
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llUpdateTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column adwl_line_logistic.ll_yn
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	private String llYn;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_id
	 * @return  the value of adwl_line_logistic.ll_id
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public Long getLlId() {
		return llId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_id
	 * @param llId  the value for adwl_line_logistic.ll_id
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlId(Long llId) {
		this.llId = llId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ms_id
	 * @return  the value of adwl_line_logistic.ms_id
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public Long getMsId() {
		return msId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ms_id
	 * @param msId  the value for adwl_line_logistic.ms_id
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setMsId(Long msId) {
		this.msId = msId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_type
	 * @return  the value of adwl_line_logistic.ll_type
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlType() {
		return llType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_type
	 * @param llType  the value for adwl_line_logistic.ll_type
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlType(String llType) {
		this.llType = llType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_departure_province
	 * @return  the value of adwl_line_logistic.ll_departure_province
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlDepartureProvince() {
		return llDepartureProvince;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_departure_province
	 * @param llDepartureProvince  the value for adwl_line_logistic.ll_departure_province
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlDepartureProvince(String llDepartureProvince) {
		this.llDepartureProvince = llDepartureProvince;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_departure_city
	 * @return  the value of adwl_line_logistic.ll_departure_city
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlDepartureCity() {
		return llDepartureCity;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_departure_city
	 * @param llDepartureCity  the value for adwl_line_logistic.ll_departure_city
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlDepartureCity(String llDepartureCity) {
		this.llDepartureCity = llDepartureCity;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_departure_area
	 * @return  the value of adwl_line_logistic.ll_departure_area
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlDepartureArea() {
		return llDepartureArea;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_departure_area
	 * @param llDepartureArea  the value for adwl_line_logistic.ll_departure_area
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlDepartureArea(String llDepartureArea) {
		this.llDepartureArea = llDepartureArea;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_departure_network
	 * @return  the value of adwl_line_logistic.ll_departure_network
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlDepartureNetwork() {
		return llDepartureNetwork;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_departure_network
	 * @param llDepartureNetwork  the value for adwl_line_logistic.ll_departure_network
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlDepartureNetwork(String llDepartureNetwork) {
		this.llDepartureNetwork = llDepartureNetwork;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_departure_address
	 * @return  the value of adwl_line_logistic.ll_departure_address
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlDepartureAddress() {
		return llDepartureAddress;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_departure_address
	 * @param llDepartureAddress  the value for adwl_line_logistic.ll_departure_address
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlDepartureAddress(String llDepartureAddress) {
		this.llDepartureAddress = llDepartureAddress;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_departure_person_name
	 * @return  the value of adwl_line_logistic.ll_departure_person_name
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlDeparturePersonName() {
		return llDeparturePersonName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_departure_person_name
	 * @param llDeparturePersonName  the value for adwl_line_logistic.ll_departure_person_name
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlDeparturePersonName(String llDeparturePersonName) {
		this.llDeparturePersonName = llDeparturePersonName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_departure_phone
	 * @return  the value of adwl_line_logistic.ll_departure_phone
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlDeparturePhone() {
		return llDeparturePhone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_departure_phone
	 * @param llDeparturePhone  the value for adwl_line_logistic.ll_departure_phone
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlDeparturePhone(String llDeparturePhone) {
		this.llDeparturePhone = llDeparturePhone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_departure_lanlline
	 * @return  the value of adwl_line_logistic.ll_departure_lanlline
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlDepartureLanlline() {
		return llDepartureLanlline;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_departure_lanlline
	 * @param llDepartureLanlline  the value for adwl_line_logistic.ll_departure_lanlline
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlDepartureLanlline(String llDepartureLanlline) {
		this.llDepartureLanlline = llDepartureLanlline;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_destination_province
	 * @return  the value of adwl_line_logistic.ll_destination_province
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlDestinationProvince() {
		return llDestinationProvince;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_destination_province
	 * @param llDestinationProvince  the value for adwl_line_logistic.ll_destination_province
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlDestinationProvince(String llDestinationProvince) {
		this.llDestinationProvince = llDestinationProvince;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_destination_city
	 * @return  the value of adwl_line_logistic.ll_destination_city
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlDestinationCity() {
		return llDestinationCity;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_destination_city
	 * @param llDestinationCity  the value for adwl_line_logistic.ll_destination_city
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlDestinationCity(String llDestinationCity) {
		this.llDestinationCity = llDestinationCity;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_destination_area
	 * @return  the value of adwl_line_logistic.ll_destination_area
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlDestinationArea() {
		return llDestinationArea;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_destination_area
	 * @param llDestinationArea  the value for adwl_line_logistic.ll_destination_area
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlDestinationArea(String llDestinationArea) {
		this.llDestinationArea = llDestinationArea;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_destination_network
	 * @return  the value of adwl_line_logistic.ll_destination_network
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlDestinationNetwork() {
		return llDestinationNetwork;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_destination_network
	 * @param llDestinationNetwork  the value for adwl_line_logistic.ll_destination_network
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlDestinationNetwork(String llDestinationNetwork) {
		this.llDestinationNetwork = llDestinationNetwork;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_destination_address
	 * @return  the value of adwl_line_logistic.ll_destination_address
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlDestinationAddress() {
		return llDestinationAddress;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_destination_address
	 * @param llDestinationAddress  the value for adwl_line_logistic.ll_destination_address
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlDestinationAddress(String llDestinationAddress) {
		this.llDestinationAddress = llDestinationAddress;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_destination_person_name
	 * @return  the value of adwl_line_logistic.ll_destination_person_name
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlDestinationPersonName() {
		return llDestinationPersonName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_destination_person_name
	 * @param llDestinationPersonName  the value for adwl_line_logistic.ll_destination_person_name
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlDestinationPersonName(String llDestinationPersonName) {
		this.llDestinationPersonName = llDestinationPersonName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_destination_phone
	 * @return  the value of adwl_line_logistic.ll_destination_phone
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlDestinationPhone() {
		return llDestinationPhone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_destination_phone
	 * @param llDestinationPhone  the value for adwl_line_logistic.ll_destination_phone
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlDestinationPhone(String llDestinationPhone) {
		this.llDestinationPhone = llDestinationPhone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_destination_lanlline
	 * @return  the value of adwl_line_logistic.ll_destination_lanlline
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlDestinationLanlline() {
		return llDestinationLanlline;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_destination_lanlline
	 * @param llDestinationLanlline  the value for adwl_line_logistic.ll_destination_lanlline
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlDestinationLanlline(String llDestinationLanlline) {
		this.llDestinationLanlline = llDestinationLanlline;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_heavy_cargo
	 * @return  the value of adwl_line_logistic.ll_heavy_cargo
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public BigDecimal getLlHeavyCargo() {
		return llHeavyCargo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_heavy_cargo
	 * @param llHeavyCargo  the value for adwl_line_logistic.ll_heavy_cargo
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlHeavyCargo(BigDecimal llHeavyCargo) {
		this.llHeavyCargo = llHeavyCargo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_light_cargo
	 * @return  the value of adwl_line_logistic.ll_light_cargo
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public BigDecimal getLlLightCargo() {
		return llLightCargo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_light_cargo
	 * @param llLightCargo  the value for adwl_line_logistic.ll_light_cargo
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlLightCargo(BigDecimal llLightCargo) {
		this.llLightCargo = llLightCargo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_minimum
	 * @return  the value of adwl_line_logistic.ll_minimum
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public BigDecimal getLlMinimum() {
		return llMinimum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_minimum
	 * @param llMinimum  the value for adwl_line_logistic.ll_minimum
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlMinimum(BigDecimal llMinimum) {
		this.llMinimum = llMinimum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_prescription
	 * @return  the value of adwl_line_logistic.ll_prescription
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlPrescription() {
		return llPrescription;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_prescription
	 * @param llPrescription  the value for adwl_line_logistic.ll_prescription
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlPrescription(String llPrescription) {
		this.llPrescription = llPrescription;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_prescription_units
	 * @return  the value of adwl_line_logistic.ll_prescription_units
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlPrescriptionUnits() {
		return llPrescriptionUnits;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_prescription_units
	 * @param llPrescriptionUnits  the value for adwl_line_logistic.ll_prescription_units
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlPrescriptionUnits(String llPrescriptionUnits) {
		this.llPrescriptionUnits = llPrescriptionUnits;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_frequency
	 * @return  the value of adwl_line_logistic.ll_frequency
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlFrequency() {
		return llFrequency;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_frequency
	 * @param llFrequency  the value for adwl_line_logistic.ll_frequency
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlFrequency(String llFrequency) {
		this.llFrequency = llFrequency;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_frequency_units
	 * @return  the value of adwl_line_logistic.ll_frequency_units
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlFrequencyUnits() {
		return llFrequencyUnits;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_frequency_units
	 * @param llFrequencyUnits  the value for adwl_line_logistic.ll_frequency_units
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlFrequencyUnits(String llFrequencyUnits) {
		this.llFrequencyUnits = llFrequencyUnits;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_car_spec
	 * @return  the value of adwl_line_logistic.ll_car_spec
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlCarSpec() {
		return llCarSpec;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_car_spec
	 * @param llCarSpec  the value for adwl_line_logistic.ll_car_spec
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlCarSpec(String llCarSpec) {
		this.llCarSpec = llCarSpec;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_status
	 * @return  the value of adwl_line_logistic.ll_status
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlStatus() {
		return llStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_status
	 * @param llStatus  the value for adwl_line_logistic.ll_status
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlStatus(String llStatus) {
		this.llStatus = llStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_descriptions
	 * @return  the value of adwl_line_logistic.ll_descriptions
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlDescriptions() {
		return llDescriptions;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_descriptions
	 * @param llDescriptions  the value for adwl_line_logistic.ll_descriptions
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlDescriptions(String llDescriptions) {
		this.llDescriptions = llDescriptions;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_create_time
	 * @return  the value of adwl_line_logistic.ll_create_time
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlCreateTime() {
		return llCreateTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_create_time
	 * @param llCreateTime  the value for adwl_line_logistic.ll_create_time
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlCreateTime(String llCreateTime) {
		this.llCreateTime = llCreateTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_update_time
	 * @return  the value of adwl_line_logistic.ll_update_time
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlUpdateTime() {
		return llUpdateTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_update_time
	 * @param llUpdateTime  the value for adwl_line_logistic.ll_update_time
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlUpdateTime(String llUpdateTime) {
		this.llUpdateTime = llUpdateTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column adwl_line_logistic.ll_yn
	 * @return  the value of adwl_line_logistic.ll_yn
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public String getLlYn() {
		return llYn;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column adwl_line_logistic.ll_yn
	 * @param llYn  the value for adwl_line_logistic.ll_yn
	 * @abatorgenerated  Thu Dec 20 13:01:58 CST 2018
	 */
	public void setLlYn(String llYn) {
		this.llYn = llYn;
	}
}