package com.ada.wuliu.shipper.front.domian.invoice;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AdwlInvoiceQualificationsExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public AdwlInvoiceQualificationsExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    protected AdwlInvoiceQualificationsExample(AdwlInvoiceQualificationsExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table adwl_invoice_qualification
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIqIdIsNull() {
            addCriterion("iq_id is null");
            return this;
        }

        public Criteria andIqIdIsNotNull() {
            addCriterion("iq_id is not null");
            return this;
        }

        public Criteria andIqIdEqualTo(Long value) {
            addCriterion("iq_id =", value, "iqId");
            return this;
        }

        public Criteria andIqIdNotEqualTo(Long value) {
            addCriterion("iq_id <>", value, "iqId");
            return this;
        }

        public Criteria andIqIdGreaterThan(Long value) {
            addCriterion("iq_id >", value, "iqId");
            return this;
        }

        public Criteria andIqIdGreaterThanOrEqualTo(Long value) {
            addCriterion("iq_id >=", value, "iqId");
            return this;
        }

        public Criteria andIqIdLessThan(Long value) {
            addCriterion("iq_id <", value, "iqId");
            return this;
        }

        public Criteria andIqIdLessThanOrEqualTo(Long value) {
            addCriterion("iq_id <=", value, "iqId");
            return this;
        }

        public Criteria andIqIdIn(List values) {
            addCriterion("iq_id in", values, "iqId");
            return this;
        }

        public Criteria andIqIdNotIn(List values) {
            addCriterion("iq_id not in", values, "iqId");
            return this;
        }

        public Criteria andIqIdBetween(Long value1, Long value2) {
            addCriterion("iq_id between", value1, value2, "iqId");
            return this;
        }

        public Criteria andIqIdNotBetween(Long value1, Long value2) {
            addCriterion("iq_id not between", value1, value2, "iqId");
            return this;
        }

        public Criteria andMsIdIsNull() {
            addCriterion("ms_id is null");
            return this;
        }

        public Criteria andMsIdIsNotNull() {
            addCriterion("ms_id is not null");
            return this;
        }

        public Criteria andMsIdEqualTo(Long value) {
            addCriterion("ms_id =", value, "msId");
            return this;
        }

        public Criteria andMsIdNotEqualTo(Long value) {
            addCriterion("ms_id <>", value, "msId");
            return this;
        }

        public Criteria andMsIdGreaterThan(Long value) {
            addCriterion("ms_id >", value, "msId");
            return this;
        }

        public Criteria andMsIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ms_id >=", value, "msId");
            return this;
        }

        public Criteria andMsIdLessThan(Long value) {
            addCriterion("ms_id <", value, "msId");
            return this;
        }

        public Criteria andMsIdLessThanOrEqualTo(Long value) {
            addCriterion("ms_id <=", value, "msId");
            return this;
        }

        public Criteria andMsIdIn(List values) {
            addCriterion("ms_id in", values, "msId");
            return this;
        }

        public Criteria andMsIdNotIn(List values) {
            addCriterion("ms_id not in", values, "msId");
            return this;
        }

        public Criteria andMsIdBetween(Long value1, Long value2) {
            addCriterion("ms_id between", value1, value2, "msId");
            return this;
        }

        public Criteria andMsIdNotBetween(Long value1, Long value2) {
            addCriterion("ms_id not between", value1, value2, "msId");
            return this;
        }

        public Criteria andMrqRoleTypeIsNull() {
            addCriterion("mrq_role_type is null");
            return this;
        }

        public Criteria andMrqRoleTypeIsNotNull() {
            addCriterion("mrq_role_type is not null");
            return this;
        }

        public Criteria andMrqRoleTypeEqualTo(Integer value) {
            addCriterion("mrq_role_type =", value, "mrqRoleType");
            return this;
        }

        public Criteria andMrqRoleTypeNotEqualTo(Integer value) {
            addCriterion("mrq_role_type <>", value, "mrqRoleType");
            return this;
        }

        public Criteria andMrqRoleTypeGreaterThan(Integer value) {
            addCriterion("mrq_role_type >", value, "mrqRoleType");
            return this;
        }

        public Criteria andMrqRoleTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("mrq_role_type >=", value, "mrqRoleType");
            return this;
        }

        public Criteria andMrqRoleTypeLessThan(Integer value) {
            addCriterion("mrq_role_type <", value, "mrqRoleType");
            return this;
        }

        public Criteria andMrqRoleTypeLessThanOrEqualTo(Integer value) {
            addCriterion("mrq_role_type <=", value, "mrqRoleType");
            return this;
        }

        public Criteria andMrqRoleTypeIn(List values) {
            addCriterion("mrq_role_type in", values, "mrqRoleType");
            return this;
        }

        public Criteria andMrqRoleTypeNotIn(List values) {
            addCriterion("mrq_role_type not in", values, "mrqRoleType");
            return this;
        }

        public Criteria andMrqRoleTypeBetween(Integer value1, Integer value2) {
            addCriterion("mrq_role_type between", value1, value2, "mrqRoleType");
            return this;
        }

        public Criteria andMrqRoleTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("mrq_role_type not between", value1, value2, "mrqRoleType");
            return this;
        }

        public Criteria andMsPhoneIsNull() {
            addCriterion("ms_phone is null");
            return this;
        }

        public Criteria andMsPhoneIsNotNull() {
            addCriterion("ms_phone is not null");
            return this;
        }

        public Criteria andMsPhoneEqualTo(String value) {
            addCriterion("ms_phone =", value, "msPhone");
            return this;
        }

        public Criteria andMsPhoneNotEqualTo(String value) {
            addCriterion("ms_phone <>", value, "msPhone");
            return this;
        }

        public Criteria andMsPhoneGreaterThan(String value) {
            addCriterion("ms_phone >", value, "msPhone");
            return this;
        }

        public Criteria andMsPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("ms_phone >=", value, "msPhone");
            return this;
        }

        public Criteria andMsPhoneLessThan(String value) {
            addCriterion("ms_phone <", value, "msPhone");
            return this;
        }

        public Criteria andMsPhoneLessThanOrEqualTo(String value) {
            addCriterion("ms_phone <=", value, "msPhone");
            return this;
        }

        public Criteria andMsPhoneLike(String value) {
            addCriterion("ms_phone like", value, "msPhone");
            return this;
        }

        public Criteria andMsPhoneNotLike(String value) {
            addCriterion("ms_phone not like", value, "msPhone");
            return this;
        }

        public Criteria andMsPhoneIn(List values) {
            addCriterion("ms_phone in", values, "msPhone");
            return this;
        }

        public Criteria andMsPhoneNotIn(List values) {
            addCriterion("ms_phone not in", values, "msPhone");
            return this;
        }

        public Criteria andMsPhoneBetween(String value1, String value2) {
            addCriterion("ms_phone between", value1, value2, "msPhone");
            return this;
        }

        public Criteria andMsPhoneNotBetween(String value1, String value2) {
            addCriterion("ms_phone not between", value1, value2, "msPhone");
            return this;
        }

        public Criteria andIqAuditStatusIsNull() {
            addCriterion("iq_audit_status is null");
            return this;
        }

        public Criteria andIqAuditStatusIsNotNull() {
            addCriterion("iq_audit_status is not null");
            return this;
        }

        public Criteria andIqAuditStatusEqualTo(Integer value) {
            addCriterion("iq_audit_status =", value, "iqAuditStatus");
            return this;
        }

        public Criteria andIqAuditStatusNotEqualTo(Integer value) {
            addCriterion("iq_audit_status <>", value, "iqAuditStatus");
            return this;
        }

        public Criteria andIqAuditStatusGreaterThan(Integer value) {
            addCriterion("iq_audit_status >", value, "iqAuditStatus");
            return this;
        }

        public Criteria andIqAuditStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("iq_audit_status >=", value, "iqAuditStatus");
            return this;
        }

        public Criteria andIqAuditStatusLessThan(Integer value) {
            addCriterion("iq_audit_status <", value, "iqAuditStatus");
            return this;
        }

        public Criteria andIqAuditStatusLessThanOrEqualTo(Integer value) {
            addCriterion("iq_audit_status <=", value, "iqAuditStatus");
            return this;
        }

        public Criteria andIqAuditStatusIn(List values) {
            addCriterion("iq_audit_status in", values, "iqAuditStatus");
            return this;
        }

        public Criteria andIqAuditStatusNotIn(List values) {
            addCriterion("iq_audit_status not in", values, "iqAuditStatus");
            return this;
        }

        public Criteria andIqAuditStatusBetween(Integer value1, Integer value2) {
            addCriterion("iq_audit_status between", value1, value2, "iqAuditStatus");
            return this;
        }

        public Criteria andIqAuditStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("iq_audit_status not between", value1, value2, "iqAuditStatus");
            return this;
        }

        public Criteria andIqCompanyNameIsNull() {
            addCriterion("iq_company_name is null");
            return this;
        }

        public Criteria andIqCompanyNameIsNotNull() {
            addCriterion("iq_company_name is not null");
            return this;
        }

        public Criteria andIqCompanyNameEqualTo(String value) {
            addCriterion("iq_company_name =", value, "iqCompanyName");
            return this;
        }

        public Criteria andIqCompanyNameNotEqualTo(String value) {
            addCriterion("iq_company_name <>", value, "iqCompanyName");
            return this;
        }

        public Criteria andIqCompanyNameGreaterThan(String value) {
            addCriterion("iq_company_name >", value, "iqCompanyName");
            return this;
        }

        public Criteria andIqCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("iq_company_name >=", value, "iqCompanyName");
            return this;
        }

        public Criteria andIqCompanyNameLessThan(String value) {
            addCriterion("iq_company_name <", value, "iqCompanyName");
            return this;
        }

        public Criteria andIqCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("iq_company_name <=", value, "iqCompanyName");
            return this;
        }

        public Criteria andIqCompanyNameLike(String value) {
            addCriterion("iq_company_name like", value, "iqCompanyName");
            return this;
        }

        public Criteria andIqCompanyNameNotLike(String value) {
            addCriterion("iq_company_name not like", value, "iqCompanyName");
            return this;
        }

        public Criteria andIqCompanyNameIn(List values) {
            addCriterion("iq_company_name in", values, "iqCompanyName");
            return this;
        }

        public Criteria andIqCompanyNameNotIn(List values) {
            addCriterion("iq_company_name not in", values, "iqCompanyName");
            return this;
        }

        public Criteria andIqCompanyNameBetween(String value1, String value2) {
            addCriterion("iq_company_name between", value1, value2, "iqCompanyName");
            return this;
        }

        public Criteria andIqCompanyNameNotBetween(String value1, String value2) {
            addCriterion("iq_company_name not between", value1, value2, "iqCompanyName");
            return this;
        }

        public Criteria andIqTaxerCodeIsNull() {
            addCriterion("iq_taxer_code is null");
            return this;
        }

        public Criteria andIqTaxerCodeIsNotNull() {
            addCriterion("iq_taxer_code is not null");
            return this;
        }

        public Criteria andIqTaxerCodeEqualTo(String value) {
            addCriterion("iq_taxer_code =", value, "iqTaxerCode");
            return this;
        }

        public Criteria andIqTaxerCodeNotEqualTo(String value) {
            addCriterion("iq_taxer_code <>", value, "iqTaxerCode");
            return this;
        }

        public Criteria andIqTaxerCodeGreaterThan(String value) {
            addCriterion("iq_taxer_code >", value, "iqTaxerCode");
            return this;
        }

        public Criteria andIqTaxerCodeGreaterThanOrEqualTo(String value) {
            addCriterion("iq_taxer_code >=", value, "iqTaxerCode");
            return this;
        }

        public Criteria andIqTaxerCodeLessThan(String value) {
            addCriterion("iq_taxer_code <", value, "iqTaxerCode");
            return this;
        }

        public Criteria andIqTaxerCodeLessThanOrEqualTo(String value) {
            addCriterion("iq_taxer_code <=", value, "iqTaxerCode");
            return this;
        }

        public Criteria andIqTaxerCodeLike(String value) {
            addCriterion("iq_taxer_code like", value, "iqTaxerCode");
            return this;
        }

        public Criteria andIqTaxerCodeNotLike(String value) {
            addCriterion("iq_taxer_code not like", value, "iqTaxerCode");
            return this;
        }

        public Criteria andIqTaxerCodeIn(List values) {
            addCriterion("iq_taxer_code in", values, "iqTaxerCode");
            return this;
        }

        public Criteria andIqTaxerCodeNotIn(List values) {
            addCriterion("iq_taxer_code not in", values, "iqTaxerCode");
            return this;
        }

        public Criteria andIqTaxerCodeBetween(String value1, String value2) {
            addCriterion("iq_taxer_code between", value1, value2, "iqTaxerCode");
            return this;
        }

        public Criteria andIqTaxerCodeNotBetween(String value1, String value2) {
            addCriterion("iq_taxer_code not between", value1, value2, "iqTaxerCode");
            return this;
        }

        public Criteria andIqCompanyAreaIsNull() {
            addCriterion("iq_company_area is null");
            return this;
        }

        public Criteria andIqCompanyAreaIsNotNull() {
            addCriterion("iq_company_area is not null");
            return this;
        }

        public Criteria andIqCompanyAreaEqualTo(String value) {
            addCriterion("iq_company_area =", value, "iqCompanyArea");
            return this;
        }

        public Criteria andIqCompanyAreaNotEqualTo(String value) {
            addCriterion("iq_company_area <>", value, "iqCompanyArea");
            return this;
        }

        public Criteria andIqCompanyAreaGreaterThan(String value) {
            addCriterion("iq_company_area >", value, "iqCompanyArea");
            return this;
        }

        public Criteria andIqCompanyAreaGreaterThanOrEqualTo(String value) {
            addCriterion("iq_company_area >=", value, "iqCompanyArea");
            return this;
        }

        public Criteria andIqCompanyAreaLessThan(String value) {
            addCriterion("iq_company_area <", value, "iqCompanyArea");
            return this;
        }

        public Criteria andIqCompanyAreaLessThanOrEqualTo(String value) {
            addCriterion("iq_company_area <=", value, "iqCompanyArea");
            return this;
        }

        public Criteria andIqCompanyAreaLike(String value) {
            addCriterion("iq_company_area like", value, "iqCompanyArea");
            return this;
        }

        public Criteria andIqCompanyAreaNotLike(String value) {
            addCriterion("iq_company_area not like", value, "iqCompanyArea");
            return this;
        }

        public Criteria andIqCompanyAreaIn(List values) {
            addCriterion("iq_company_area in", values, "iqCompanyArea");
            return this;
        }

        public Criteria andIqCompanyAreaNotIn(List values) {
            addCriterion("iq_company_area not in", values, "iqCompanyArea");
            return this;
        }

        public Criteria andIqCompanyAreaBetween(String value1, String value2) {
            addCriterion("iq_company_area between", value1, value2, "iqCompanyArea");
            return this;
        }

        public Criteria andIqCompanyAreaNotBetween(String value1, String value2) {
            addCriterion("iq_company_area not between", value1, value2, "iqCompanyArea");
            return this;
        }

        public Criteria andIqDetAddressIsNull() {
            addCriterion("iq_det_address is null");
            return this;
        }

        public Criteria andIqDetAddressIsNotNull() {
            addCriterion("iq_det_address is not null");
            return this;
        }

        public Criteria andIqDetAddressEqualTo(String value) {
            addCriterion("iq_det_address =", value, "iqDetAddress");
            return this;
        }

        public Criteria andIqDetAddressNotEqualTo(String value) {
            addCriterion("iq_det_address <>", value, "iqDetAddress");
            return this;
        }

        public Criteria andIqDetAddressGreaterThan(String value) {
            addCriterion("iq_det_address >", value, "iqDetAddress");
            return this;
        }

        public Criteria andIqDetAddressGreaterThanOrEqualTo(String value) {
            addCriterion("iq_det_address >=", value, "iqDetAddress");
            return this;
        }

        public Criteria andIqDetAddressLessThan(String value) {
            addCriterion("iq_det_address <", value, "iqDetAddress");
            return this;
        }

        public Criteria andIqDetAddressLessThanOrEqualTo(String value) {
            addCriterion("iq_det_address <=", value, "iqDetAddress");
            return this;
        }

        public Criteria andIqDetAddressLike(String value) {
            addCriterion("iq_det_address like", value, "iqDetAddress");
            return this;
        }

        public Criteria andIqDetAddressNotLike(String value) {
            addCriterion("iq_det_address not like", value, "iqDetAddress");
            return this;
        }

        public Criteria andIqDetAddressIn(List values) {
            addCriterion("iq_det_address in", values, "iqDetAddress");
            return this;
        }

        public Criteria andIqDetAddressNotIn(List values) {
            addCriterion("iq_det_address not in", values, "iqDetAddress");
            return this;
        }

        public Criteria andIqDetAddressBetween(String value1, String value2) {
            addCriterion("iq_det_address between", value1, value2, "iqDetAddress");
            return this;
        }

        public Criteria andIqDetAddressNotBetween(String value1, String value2) {
            addCriterion("iq_det_address not between", value1, value2, "iqDetAddress");
            return this;
        }

        public Criteria andIqCompanyTelphoneIsNull() {
            addCriterion("iq_company_telphone is null");
            return this;
        }

        public Criteria andIqCompanyTelphoneIsNotNull() {
            addCriterion("iq_company_telphone is not null");
            return this;
        }

        public Criteria andIqCompanyTelphoneEqualTo(String value) {
            addCriterion("iq_company_telphone =", value, "iqCompanyTelphone");
            return this;
        }

        public Criteria andIqCompanyTelphoneNotEqualTo(String value) {
            addCriterion("iq_company_telphone <>", value, "iqCompanyTelphone");
            return this;
        }

        public Criteria andIqCompanyTelphoneGreaterThan(String value) {
            addCriterion("iq_company_telphone >", value, "iqCompanyTelphone");
            return this;
        }

        public Criteria andIqCompanyTelphoneGreaterThanOrEqualTo(String value) {
            addCriterion("iq_company_telphone >=", value, "iqCompanyTelphone");
            return this;
        }

        public Criteria andIqCompanyTelphoneLessThan(String value) {
            addCriterion("iq_company_telphone <", value, "iqCompanyTelphone");
            return this;
        }

        public Criteria andIqCompanyTelphoneLessThanOrEqualTo(String value) {
            addCriterion("iq_company_telphone <=", value, "iqCompanyTelphone");
            return this;
        }

        public Criteria andIqCompanyTelphoneLike(String value) {
            addCriterion("iq_company_telphone like", value, "iqCompanyTelphone");
            return this;
        }

        public Criteria andIqCompanyTelphoneNotLike(String value) {
            addCriterion("iq_company_telphone not like", value, "iqCompanyTelphone");
            return this;
        }

        public Criteria andIqCompanyTelphoneIn(List values) {
            addCriterion("iq_company_telphone in", values, "iqCompanyTelphone");
            return this;
        }

        public Criteria andIqCompanyTelphoneNotIn(List values) {
            addCriterion("iq_company_telphone not in", values, "iqCompanyTelphone");
            return this;
        }

        public Criteria andIqCompanyTelphoneBetween(String value1, String value2) {
            addCriterion("iq_company_telphone between", value1, value2, "iqCompanyTelphone");
            return this;
        }

        public Criteria andIqCompanyTelphoneNotBetween(String value1, String value2) {
            addCriterion("iq_company_telphone not between", value1, value2, "iqCompanyTelphone");
            return this;
        }

        public Criteria andIqCompanyOpenBankIsNull() {
            addCriterion("iq_company_open_bank is null");
            return this;
        }

        public Criteria andIqCompanyOpenBankIsNotNull() {
            addCriterion("iq_company_open_bank is not null");
            return this;
        }

        public Criteria andIqCompanyOpenBankEqualTo(String value) {
            addCriterion("iq_company_open_bank =", value, "iqCompanyOpenBank");
            return this;
        }

        public Criteria andIqCompanyOpenBankNotEqualTo(String value) {
            addCriterion("iq_company_open_bank <>", value, "iqCompanyOpenBank");
            return this;
        }

        public Criteria andIqCompanyOpenBankGreaterThan(String value) {
            addCriterion("iq_company_open_bank >", value, "iqCompanyOpenBank");
            return this;
        }

        public Criteria andIqCompanyOpenBankGreaterThanOrEqualTo(String value) {
            addCriterion("iq_company_open_bank >=", value, "iqCompanyOpenBank");
            return this;
        }

        public Criteria andIqCompanyOpenBankLessThan(String value) {
            addCriterion("iq_company_open_bank <", value, "iqCompanyOpenBank");
            return this;
        }

        public Criteria andIqCompanyOpenBankLessThanOrEqualTo(String value) {
            addCriterion("iq_company_open_bank <=", value, "iqCompanyOpenBank");
            return this;
        }

        public Criteria andIqCompanyOpenBankLike(String value) {
            addCriterion("iq_company_open_bank like", value, "iqCompanyOpenBank");
            return this;
        }

        public Criteria andIqCompanyOpenBankNotLike(String value) {
            addCriterion("iq_company_open_bank not like", value, "iqCompanyOpenBank");
            return this;
        }

        public Criteria andIqCompanyOpenBankIn(List values) {
            addCriterion("iq_company_open_bank in", values, "iqCompanyOpenBank");
            return this;
        }

        public Criteria andIqCompanyOpenBankNotIn(List values) {
            addCriterion("iq_company_open_bank not in", values, "iqCompanyOpenBank");
            return this;
        }

        public Criteria andIqCompanyOpenBankBetween(String value1, String value2) {
            addCriterion("iq_company_open_bank between", value1, value2, "iqCompanyOpenBank");
            return this;
        }

        public Criteria andIqCompanyOpenBankNotBetween(String value1, String value2) {
            addCriterion("iq_company_open_bank not between", value1, value2, "iqCompanyOpenBank");
            return this;
        }

        public Criteria andIqOpenBankAccountIsNull() {
            addCriterion("iq_open_bank_account is null");
            return this;
        }

        public Criteria andIqOpenBankAccountIsNotNull() {
            addCriterion("iq_open_bank_account is not null");
            return this;
        }

        public Criteria andIqOpenBankAccountEqualTo(String value) {
            addCriterion("iq_open_bank_account =", value, "iqOpenBankAccount");
            return this;
        }

        public Criteria andIqOpenBankAccountNotEqualTo(String value) {
            addCriterion("iq_open_bank_account <>", value, "iqOpenBankAccount");
            return this;
        }

        public Criteria andIqOpenBankAccountGreaterThan(String value) {
            addCriterion("iq_open_bank_account >", value, "iqOpenBankAccount");
            return this;
        }

        public Criteria andIqOpenBankAccountGreaterThanOrEqualTo(String value) {
            addCriterion("iq_open_bank_account >=", value, "iqOpenBankAccount");
            return this;
        }

        public Criteria andIqOpenBankAccountLessThan(String value) {
            addCriterion("iq_open_bank_account <", value, "iqOpenBankAccount");
            return this;
        }

        public Criteria andIqOpenBankAccountLessThanOrEqualTo(String value) {
            addCriterion("iq_open_bank_account <=", value, "iqOpenBankAccount");
            return this;
        }

        public Criteria andIqOpenBankAccountLike(String value) {
            addCriterion("iq_open_bank_account like", value, "iqOpenBankAccount");
            return this;
        }

        public Criteria andIqOpenBankAccountNotLike(String value) {
            addCriterion("iq_open_bank_account not like", value, "iqOpenBankAccount");
            return this;
        }

        public Criteria andIqOpenBankAccountIn(List values) {
            addCriterion("iq_open_bank_account in", values, "iqOpenBankAccount");
            return this;
        }

        public Criteria andIqOpenBankAccountNotIn(List values) {
            addCriterion("iq_open_bank_account not in", values, "iqOpenBankAccount");
            return this;
        }

        public Criteria andIqOpenBankAccountBetween(String value1, String value2) {
            addCriterion("iq_open_bank_account between", value1, value2, "iqOpenBankAccount");
            return this;
        }

        public Criteria andIqOpenBankAccountNotBetween(String value1, String value2) {
            addCriterion("iq_open_bank_account not between", value1, value2, "iqOpenBankAccount");
            return this;
        }

        public Criteria andIqBussinessLicensePicIsNull() {
            addCriterion("iq_bussiness_license_pic is null");
            return this;
        }

        public Criteria andIqBussinessLicensePicIsNotNull() {
            addCriterion("iq_bussiness_license_pic is not null");
            return this;
        }

        public Criteria andIqBussinessLicensePicEqualTo(String value) {
            addCriterion("iq_bussiness_license_pic =", value, "iqBussinessLicensePic");
            return this;
        }

        public Criteria andIqBussinessLicensePicNotEqualTo(String value) {
            addCriterion("iq_bussiness_license_pic <>", value, "iqBussinessLicensePic");
            return this;
        }

        public Criteria andIqBussinessLicensePicGreaterThan(String value) {
            addCriterion("iq_bussiness_license_pic >", value, "iqBussinessLicensePic");
            return this;
        }

        public Criteria andIqBussinessLicensePicGreaterThanOrEqualTo(String value) {
            addCriterion("iq_bussiness_license_pic >=", value, "iqBussinessLicensePic");
            return this;
        }

        public Criteria andIqBussinessLicensePicLessThan(String value) {
            addCriterion("iq_bussiness_license_pic <", value, "iqBussinessLicensePic");
            return this;
        }

        public Criteria andIqBussinessLicensePicLessThanOrEqualTo(String value) {
            addCriterion("iq_bussiness_license_pic <=", value, "iqBussinessLicensePic");
            return this;
        }

        public Criteria andIqBussinessLicensePicLike(String value) {
            addCriterion("iq_bussiness_license_pic like", value, "iqBussinessLicensePic");
            return this;
        }

        public Criteria andIqBussinessLicensePicNotLike(String value) {
            addCriterion("iq_bussiness_license_pic not like", value, "iqBussinessLicensePic");
            return this;
        }

        public Criteria andIqBussinessLicensePicIn(List values) {
            addCriterion("iq_bussiness_license_pic in", values, "iqBussinessLicensePic");
            return this;
        }

        public Criteria andIqBussinessLicensePicNotIn(List values) {
            addCriterion("iq_bussiness_license_pic not in", values, "iqBussinessLicensePic");
            return this;
        }

        public Criteria andIqBussinessLicensePicBetween(String value1, String value2) {
            addCriterion("iq_bussiness_license_pic between", value1, value2, "iqBussinessLicensePic");
            return this;
        }

        public Criteria andIqBussinessLicensePicNotBetween(String value1, String value2) {
            addCriterion("iq_bussiness_license_pic not between", value1, value2, "iqBussinessLicensePic");
            return this;
        }

        public Criteria andIqOtherzPicIsNull() {
            addCriterion("iq_otherz_pic is null");
            return this;
        }

        public Criteria andIqOtherzPicIsNotNull() {
            addCriterion("iq_otherz_pic is not null");
            return this;
        }

        public Criteria andIqOtherzPicEqualTo(String value) {
            addCriterion("iq_otherz_pic =", value, "iqOtherzPic");
            return this;
        }

        public Criteria andIqOtherzPicNotEqualTo(String value) {
            addCriterion("iq_otherz_pic <>", value, "iqOtherzPic");
            return this;
        }

        public Criteria andIqOtherzPicGreaterThan(String value) {
            addCriterion("iq_otherz_pic >", value, "iqOtherzPic");
            return this;
        }

        public Criteria andIqOtherzPicGreaterThanOrEqualTo(String value) {
            addCriterion("iq_otherz_pic >=", value, "iqOtherzPic");
            return this;
        }

        public Criteria andIqOtherzPicLessThan(String value) {
            addCriterion("iq_otherz_pic <", value, "iqOtherzPic");
            return this;
        }

        public Criteria andIqOtherzPicLessThanOrEqualTo(String value) {
            addCriterion("iq_otherz_pic <=", value, "iqOtherzPic");
            return this;
        }

        public Criteria andIqOtherzPicLike(String value) {
            addCriterion("iq_otherz_pic like", value, "iqOtherzPic");
            return this;
        }

        public Criteria andIqOtherzPicNotLike(String value) {
            addCriterion("iq_otherz_pic not like", value, "iqOtherzPic");
            return this;
        }

        public Criteria andIqOtherzPicIn(List values) {
            addCriterion("iq_otherz_pic in", values, "iqOtherzPic");
            return this;
        }

        public Criteria andIqOtherzPicNotIn(List values) {
            addCriterion("iq_otherz_pic not in", values, "iqOtherzPic");
            return this;
        }

        public Criteria andIqOtherzPicBetween(String value1, String value2) {
            addCriterion("iq_otherz_pic between", value1, value2, "iqOtherzPic");
            return this;
        }

        public Criteria andIqOtherzPicNotBetween(String value1, String value2) {
            addCriterion("iq_otherz_pic not between", value1, value2, "iqOtherzPic");
            return this;
        }

        public Criteria andIqAuditIdIsNull() {
            addCriterion("iq_audit_id is null");
            return this;
        }

        public Criteria andIqAuditIdIsNotNull() {
            addCriterion("iq_audit_id is not null");
            return this;
        }

        public Criteria andIqAuditIdEqualTo(Long value) {
            addCriterion("iq_audit_id =", value, "iqAuditId");
            return this;
        }

        public Criteria andIqAuditIdNotEqualTo(Long value) {
            addCriterion("iq_audit_id <>", value, "iqAuditId");
            return this;
        }

        public Criteria andIqAuditIdGreaterThan(Long value) {
            addCriterion("iq_audit_id >", value, "iqAuditId");
            return this;
        }

        public Criteria andIqAuditIdGreaterThanOrEqualTo(Long value) {
            addCriterion("iq_audit_id >=", value, "iqAuditId");
            return this;
        }

        public Criteria andIqAuditIdLessThan(Long value) {
            addCriterion("iq_audit_id <", value, "iqAuditId");
            return this;
        }

        public Criteria andIqAuditIdLessThanOrEqualTo(Long value) {
            addCriterion("iq_audit_id <=", value, "iqAuditId");
            return this;
        }

        public Criteria andIqAuditIdIn(List values) {
            addCriterion("iq_audit_id in", values, "iqAuditId");
            return this;
        }

        public Criteria andIqAuditIdNotIn(List values) {
            addCriterion("iq_audit_id not in", values, "iqAuditId");
            return this;
        }

        public Criteria andIqAuditIdBetween(Long value1, Long value2) {
            addCriterion("iq_audit_id between", value1, value2, "iqAuditId");
            return this;
        }

        public Criteria andIqAuditIdNotBetween(Long value1, Long value2) {
            addCriterion("iq_audit_id not between", value1, value2, "iqAuditId");
            return this;
        }

        public Criteria andIqAuditPersonIsNull() {
            addCriterion("iq_audit_person is null");
            return this;
        }

        public Criteria andIqAuditPersonIsNotNull() {
            addCriterion("iq_audit_person is not null");
            return this;
        }

        public Criteria andIqAuditPersonEqualTo(String value) {
            addCriterion("iq_audit_person =", value, "iqAuditPerson");
            return this;
        }

        public Criteria andIqAuditPersonNotEqualTo(String value) {
            addCriterion("iq_audit_person <>", value, "iqAuditPerson");
            return this;
        }

        public Criteria andIqAuditPersonGreaterThan(String value) {
            addCriterion("iq_audit_person >", value, "iqAuditPerson");
            return this;
        }

        public Criteria andIqAuditPersonGreaterThanOrEqualTo(String value) {
            addCriterion("iq_audit_person >=", value, "iqAuditPerson");
            return this;
        }

        public Criteria andIqAuditPersonLessThan(String value) {
            addCriterion("iq_audit_person <", value, "iqAuditPerson");
            return this;
        }

        public Criteria andIqAuditPersonLessThanOrEqualTo(String value) {
            addCriterion("iq_audit_person <=", value, "iqAuditPerson");
            return this;
        }

        public Criteria andIqAuditPersonLike(String value) {
            addCriterion("iq_audit_person like", value, "iqAuditPerson");
            return this;
        }

        public Criteria andIqAuditPersonNotLike(String value) {
            addCriterion("iq_audit_person not like", value, "iqAuditPerson");
            return this;
        }

        public Criteria andIqAuditPersonIn(List values) {
            addCriterion("iq_audit_person in", values, "iqAuditPerson");
            return this;
        }

        public Criteria andIqAuditPersonNotIn(List values) {
            addCriterion("iq_audit_person not in", values, "iqAuditPerson");
            return this;
        }

        public Criteria andIqAuditPersonBetween(String value1, String value2) {
            addCriterion("iq_audit_person between", value1, value2, "iqAuditPerson");
            return this;
        }

        public Criteria andIqAuditPersonNotBetween(String value1, String value2) {
            addCriterion("iq_audit_person not between", value1, value2, "iqAuditPerson");
            return this;
        }

        public Criteria andIqYnIsNull() {
            addCriterion("iq_yn is null");
            return this;
        }

        public Criteria andIqYnIsNotNull() {
            addCriterion("iq_yn is not null");
            return this;
        }

        public Criteria andIqYnEqualTo(Integer value) {
            addCriterion("iq_yn =", value, "iqYn");
            return this;
        }

        public Criteria andIqYnNotEqualTo(Integer value) {
            addCriterion("iq_yn <>", value, "iqYn");
            return this;
        }

        public Criteria andIqYnGreaterThan(Integer value) {
            addCriterion("iq_yn >", value, "iqYn");
            return this;
        }

        public Criteria andIqYnGreaterThanOrEqualTo(Integer value) {
            addCriterion("iq_yn >=", value, "iqYn");
            return this;
        }

        public Criteria andIqYnLessThan(Integer value) {
            addCriterion("iq_yn <", value, "iqYn");
            return this;
        }

        public Criteria andIqYnLessThanOrEqualTo(Integer value) {
            addCriterion("iq_yn <=", value, "iqYn");
            return this;
        }

        public Criteria andIqYnIn(List values) {
            addCriterion("iq_yn in", values, "iqYn");
            return this;
        }

        public Criteria andIqYnNotIn(List values) {
            addCriterion("iq_yn not in", values, "iqYn");
            return this;
        }

        public Criteria andIqYnBetween(Integer value1, Integer value2) {
            addCriterion("iq_yn between", value1, value2, "iqYn");
            return this;
        }

        public Criteria andIqYnNotBetween(Integer value1, Integer value2) {
            addCriterion("iq_yn not between", value1, value2, "iqYn");
            return this;
        }

        public Criteria andCreateDatetimeIsNull() {
            addCriterion("create_datetime is null");
            return this;
        }

        public Criteria andCreateDatetimeIsNotNull() {
            addCriterion("create_datetime is not null");
            return this;
        }

        public Criteria andCreateDatetimeEqualTo(String value) {
            addCriterion("create_datetime =", value, "createDatetime");
            return this;
        }

        public Criteria andCreateDatetimeNotEqualTo(String value) {
            addCriterion("create_datetime <>", value, "createDatetime");
            return this;
        }

        public Criteria andCreateDatetimeGreaterThan(String value) {
            addCriterion("create_datetime >", value, "createDatetime");
            return this;
        }

        public Criteria andCreateDatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("create_datetime >=", value, "createDatetime");
            return this;
        }

        public Criteria andCreateDatetimeLessThan(String value) {
            addCriterion("create_datetime <", value, "createDatetime");
            return this;
        }

        public Criteria andCreateDatetimeLessThanOrEqualTo(String value) {
            addCriterion("create_datetime <=", value, "createDatetime");
            return this;
        }

        public Criteria andCreateDatetimeIn(List values) {
            addCriterion("create_datetime in", values, "createDatetime");
            return this;
        }

        public Criteria andCreateDatetimeNotIn(List values) {
            addCriterion("create_datetime not in", values, "createDatetime");
            return this;
        }

        public Criteria andCreateDatetimeBetween(String value1, String value2) {
            addCriterion("create_datetime between", value1, value2, "createDatetime");
            return this;
        }

        public Criteria andCreateDatetimeNotBetween(String value1, String value2) {
            addCriterion("create_datetime not between", value1, value2, "createDatetime");
            return this;
        }

        public Criteria andUpdateDatetimeIsNull() {
            addCriterion("update_datetime is null");
            return this;
        }

        public Criteria andUpdateDatetimeIsNotNull() {
            addCriterion("update_datetime is not null");
            return this;
        }

        public Criteria andUpdateDatetimeEqualTo(String value) {
            addCriterion("update_datetime =", value, "updateDatetime");
            return this;
        }

        public Criteria andUpdateDatetimeNotEqualTo(String value) {
            addCriterion("update_datetime <>", value, "updateDatetime");
            return this;
        }

        public Criteria andUpdateDatetimeGreaterThan(String value) {
            addCriterion("update_datetime >", value, "updateDatetime");
            return this;
        }

        public Criteria andUpdateDatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("update_datetime >=", value, "updateDatetime");
            return this;
        }

        public Criteria andUpdateDatetimeLessThan(String value) {
            addCriterion("update_datetime <", value, "updateDatetime");
            return this;
        }

        public Criteria andUpdateDatetimeLessThanOrEqualTo(String value) {
            addCriterion("update_datetime <=", value, "updateDatetime");
            return this;
        }

        public Criteria andUpdateDatetimeIn(List values) {
            addCriterion("update_datetime in", values, "updateDatetime");
            return this;
        }

        public Criteria andUpdateDatetimeNotIn(List values) {
            addCriterion("update_datetime not in", values, "updateDatetime");
            return this;
        }

        public Criteria andUpdateDatetimeBetween(String value1, String value2) {
            addCriterion("update_datetime between", value1, value2, "updateDatetime");
            return this;
        }

        public Criteria andUpdateDatetimeNotBetween(String value1, String value2) {
            addCriterion("update_datetime not between", value1, value2, "updateDatetime");
            return this;
        }

        public Criteria andAuditDatetimeIsNull() {
            addCriterion("audit_datetime is null");
            return this;
        }

        public Criteria andAuditDatetimeIsNotNull() {
            addCriterion("audit_datetime is not null");
            return this;
        }

        public Criteria andAuditDatetimeEqualTo(String value) {
            addCriterion("audit_datetime =", value, "auditDatetime");
            return this;
        }

        public Criteria andAuditDatetimeNotEqualTo(String value) {
            addCriterion("audit_datetime <>", value, "auditDatetime");
            return this;
        }

        public Criteria andAuditDatetimeGreaterThan(String value) {
            addCriterion("audit_datetime >", value, "auditDatetime");
            return this;
        }

        public Criteria andAuditDatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("audit_datetime >=", value, "auditDatetime");
            return this;
        }

        public Criteria andAuditDatetimeLessThan(String value) {
            addCriterion("audit_datetime <", value, "auditDatetime");
            return this;
        }

        public Criteria andAuditDatetimeLessThanOrEqualTo(String value) {
            addCriterion("audit_datetime <=", value, "auditDatetime");
            return this;
        }

        public Criteria andAuditDatetimeIn(List values) {
            addCriterion("audit_datetime in", values, "auditDatetime");
            return this;
        }

        public Criteria andAuditDatetimeNotIn(List values) {
            addCriterion("audit_datetime not in", values, "auditDatetime");
            return this;
        }

        public Criteria andAuditDatetimeBetween(String value1, String value2) {
            addCriterion("audit_datetime between", value1, value2, "auditDatetime");
            return this;
        }

        public Criteria andAuditDatetimeNotBetween(String value1, String value2) {
            addCriterion("audit_datetime not between", value1, value2, "auditDatetime");
            return this;
        }

        public Criteria andIqReserveOneIsNull() {
            addCriterion("iq_reserve_one is null");
            return this;
        }

        public Criteria andIqReserveOneIsNotNull() {
            addCriterion("iq_reserve_one is not null");
            return this;
        }

        public Criteria andIqReserveOneEqualTo(Integer value) {
            addCriterion("iq_reserve_one =", value, "iqReserveOne");
            return this;
        }

        public Criteria andIqReserveOneNotEqualTo(Integer value) {
            addCriterion("iq_reserve_one <>", value, "iqReserveOne");
            return this;
        }

        public Criteria andIqReserveOneGreaterThan(Integer value) {
            addCriterion("iq_reserve_one >", value, "iqReserveOne");
            return this;
        }

        public Criteria andIqReserveOneGreaterThanOrEqualTo(Integer value) {
            addCriterion("iq_reserve_one >=", value, "iqReserveOne");
            return this;
        }

        public Criteria andIqReserveOneLessThan(Integer value) {
            addCriterion("iq_reserve_one <", value, "iqReserveOne");
            return this;
        }

        public Criteria andIqReserveOneLessThanOrEqualTo(Integer value) {
            addCriterion("iq_reserve_one <=", value, "iqReserveOne");
            return this;
        }

        public Criteria andIqReserveOneIn(List values) {
            addCriterion("iq_reserve_one in", values, "iqReserveOne");
            return this;
        }

        public Criteria andIqReserveOneNotIn(List values) {
            addCriterion("iq_reserve_one not in", values, "iqReserveOne");
            return this;
        }

        public Criteria andIqReserveOneBetween(Integer value1, Integer value2) {
            addCriterion("iq_reserve_one between", value1, value2, "iqReserveOne");
            return this;
        }

        public Criteria andIqReserveOneNotBetween(Integer value1, Integer value2) {
            addCriterion("iq_reserve_one not between", value1, value2, "iqReserveOne");
            return this;
        }

        public Criteria andIqReserveTwoIsNull() {
            addCriterion("iq_reserve_two is null");
            return this;
        }

        public Criteria andIqReserveTwoIsNotNull() {
            addCriterion("iq_reserve_two is not null");
            return this;
        }

        public Criteria andIqReserveTwoEqualTo(String value) {
            addCriterion("iq_reserve_two =", value, "iqReserveTwo");
            return this;
        }

        public Criteria andIqReserveTwoNotEqualTo(String value) {
            addCriterion("iq_reserve_two <>", value, "iqReserveTwo");
            return this;
        }

        public Criteria andIqReserveTwoGreaterThan(String value) {
            addCriterion("iq_reserve_two >", value, "iqReserveTwo");
            return this;
        }

        public Criteria andIqReserveTwoGreaterThanOrEqualTo(String value) {
            addCriterion("iq_reserve_two >=", value, "iqReserveTwo");
            return this;
        }

        public Criteria andIqReserveTwoLessThan(String value) {
            addCriterion("iq_reserve_two <", value, "iqReserveTwo");
            return this;
        }

        public Criteria andIqReserveTwoLessThanOrEqualTo(String value) {
            addCriterion("iq_reserve_two <=", value, "iqReserveTwo");
            return this;
        }

        public Criteria andIqReserveTwoLike(String value) {
            addCriterion("iq_reserve_two like", value, "iqReserveTwo");
            return this;
        }

        public Criteria andIqReserveTwoNotLike(String value) {
            addCriterion("iq_reserve_two not like", value, "iqReserveTwo");
            return this;
        }

        public Criteria andIqReserveTwoIn(List values) {
            addCriterion("iq_reserve_two in", values, "iqReserveTwo");
            return this;
        }

        public Criteria andIqReserveTwoNotIn(List values) {
            addCriterion("iq_reserve_two not in", values, "iqReserveTwo");
            return this;
        }

        public Criteria andIqReserveTwoBetween(String value1, String value2) {
            addCriterion("iq_reserve_two between", value1, value2, "iqReserveTwo");
            return this;
        }

        public Criteria andIqReserveTwoNotBetween(String value1, String value2) {
            addCriterion("iq_reserve_two not between", value1, value2, "iqReserveTwo");
            return this;
        }

        public Criteria andIqReserveThreeIsNull() {
            addCriterion("iq_reserve_three is null");
            return this;
        }

        public Criteria andIqReserveThreeIsNotNull() {
            addCriterion("iq_reserve_three is not null");
            return this;
        }

        public Criteria andIqReserveThreeEqualTo(String value) {
            addCriterion("iq_reserve_three =", value, "iqReserveThree");
            return this;
        }

        public Criteria andIqReserveThreeNotEqualTo(String value) {
            addCriterion("iq_reserve_three <>", value, "iqReserveThree");
            return this;
        }

        public Criteria andIqReserveThreeGreaterThan(String value) {
            addCriterion("iq_reserve_three >", value, "iqReserveThree");
            return this;
        }

        public Criteria andIqReserveThreeGreaterThanOrEqualTo(String value) {
            addCriterion("iq_reserve_three >=", value, "iqReserveThree");
            return this;
        }

        public Criteria andIqReserveThreeLessThan(String value) {
            addCriterion("iq_reserve_three <", value, "iqReserveThree");
            return this;
        }

        public Criteria andIqReserveThreeLessThanOrEqualTo(String value) {
            addCriterion("iq_reserve_three <=", value, "iqReserveThree");
            return this;
        }

        public Criteria andIqReserveThreeLike(String value) {
            addCriterion("iq_reserve_three like", value, "iqReserveThree");
            return this;
        }

        public Criteria andIqReserveThreeNotLike(String value) {
            addCriterion("iq_reserve_three not like", value, "iqReserveThree");
            return this;
        }

        public Criteria andIqReserveThreeIn(List values) {
            addCriterion("iq_reserve_three in", values, "iqReserveThree");
            return this;
        }

        public Criteria andIqReserveThreeNotIn(List values) {
            addCriterion("iq_reserve_three not in", values, "iqReserveThree");
            return this;
        }

        public Criteria andIqReserveThreeBetween(String value1, String value2) {
            addCriterion("iq_reserve_three between", value1, value2, "iqReserveThree");
            return this;
        }

        public Criteria andIqReserveThreeNotBetween(String value1, String value2) {
            addCriterion("iq_reserve_three not between", value1, value2, "iqReserveThree");
            return this;
        }

        public Criteria andDemoIsNull() {
            addCriterion("demo is null");
            return this;
        }

        public Criteria andDemoIsNotNull() {
            addCriterion("demo is not null");
            return this;
        }

        public Criteria andDemoEqualTo(String value) {
            addCriterion("demo =", value, "demo");
            return this;
        }

        public Criteria andDemoNotEqualTo(String value) {
            addCriterion("demo <>", value, "demo");
            return this;
        }

        public Criteria andDemoGreaterThan(String value) {
            addCriterion("demo >", value, "demo");
            return this;
        }

        public Criteria andDemoGreaterThanOrEqualTo(String value) {
            addCriterion("demo >=", value, "demo");
            return this;
        }

        public Criteria andDemoLessThan(String value) {
            addCriterion("demo <", value, "demo");
            return this;
        }

        public Criteria andDemoLessThanOrEqualTo(String value) {
            addCriterion("demo <=", value, "demo");
            return this;
        }

        public Criteria andDemoLike(String value) {
            addCriterion("demo like", value, "demo");
            return this;
        }

        public Criteria andDemoNotLike(String value) {
            addCriterion("demo not like", value, "demo");
            return this;
        }

        public Criteria andDemoIn(List values) {
            addCriterion("demo in", values, "demo");
            return this;
        }

        public Criteria andDemoNotIn(List values) {
            addCriterion("demo not in", values, "demo");
            return this;
        }

        public Criteria andDemoBetween(String value1, String value2) {
            addCriterion("demo between", value1, value2, "demo");
            return this;
        }

        public Criteria andDemoNotBetween(String value1, String value2) {
            addCriterion("demo not between", value1, value2, "demo");
            return this;
        }
    }
}