package com.ada.wuliu.shipper.front.domian.invoice;

public class AdwlInvoiceQualifications {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column adwl_invoice_qualification.iq_id
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private Long iqId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column adwl_invoice_qualification.ms_id
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private Long msId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column adwl_invoice_qualification.mrq_role_type
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private Integer mrqRoleType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column adwl_invoice_qualification.ms_phone
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private String msPhone;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column adwl_invoice_qualification.iq_audit_status
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private Integer iqAuditStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column adwl_invoice_qualification.iq_company_name
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private String iqCompanyName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column adwl_invoice_qualification.iq_taxer_code
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private String iqTaxerCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column adwl_invoice_qualification.iq_company_area
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private String iqCompanyArea;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column adwl_invoice_qualification.iq_det_address
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private String iqDetAddress;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column adwl_invoice_qualification.iq_company_telphone
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private String iqCompanyTelphone;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column adwl_invoice_qualification.iq_company_open_bank
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private String iqCompanyOpenBank;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column adwl_invoice_qualification.iq_open_bank_account
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private String iqOpenBankAccount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column adwl_invoice_qualification.iq_bussiness_license_pic
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private String iqBussinessLicensePic;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column adwl_invoice_qualification.iq_otherz_pic
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private String iqOtherzPic;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column adwl_invoice_qualification.iq_audit_id
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private Long iqAuditId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column adwl_invoice_qualification.iq_audit_person
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private String iqAuditPerson;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column adwl_invoice_qualification.iq_yn
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private Integer iqYn;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column adwl_invoice_qualification.create_datetime
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private String createDatetime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column adwl_invoice_qualification.update_datetime
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private String updateDatetime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column adwl_invoice_qualification.audit_datetime
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private String auditDatetime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column adwl_invoice_qualification.iq_reserve_one
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private Integer iqReserveOne;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column adwl_invoice_qualification.iq_reserve_two
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private String iqReserveTwo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column adwl_invoice_qualification.iq_reserve_three
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private String iqReserveThree;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column adwl_invoice_qualification.demo
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    private String demo;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column adwl_invoice_qualification.iq_id
     *
     * @return the value of adwl_invoice_qualification.iq_id
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public Long getIqId() {
        return iqId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column adwl_invoice_qualification.iq_id
     *
     * @param iqId the value for adwl_invoice_qualification.iq_id
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setIqId(Long iqId) {
        this.iqId = iqId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column adwl_invoice_qualification.ms_id
     *
     * @return the value of adwl_invoice_qualification.ms_id
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public Long getMsId() {
        return msId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column adwl_invoice_qualification.ms_id
     *
     * @param msId the value for adwl_invoice_qualification.ms_id
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setMsId(Long msId) {
        this.msId = msId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column adwl_invoice_qualification.mrq_role_type
     *
     * @return the value of adwl_invoice_qualification.mrq_role_type
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public Integer getMrqRoleType() {
        return mrqRoleType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column adwl_invoice_qualification.mrq_role_type
     *
     * @param mrqRoleType the value for adwl_invoice_qualification.mrq_role_type
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setMrqRoleType(Integer mrqRoleType) {
        this.mrqRoleType = mrqRoleType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column adwl_invoice_qualification.ms_phone
     *
     * @return the value of adwl_invoice_qualification.ms_phone
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public String getMsPhone() {
        return msPhone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column adwl_invoice_qualification.ms_phone
     *
     * @param msPhone the value for adwl_invoice_qualification.ms_phone
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setMsPhone(String msPhone) {
        this.msPhone = msPhone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column adwl_invoice_qualification.iq_audit_status
     *
     * @return the value of adwl_invoice_qualification.iq_audit_status
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public Integer getIqAuditStatus() {
        return iqAuditStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column adwl_invoice_qualification.iq_audit_status
     *
     * @param iqAuditStatus the value for adwl_invoice_qualification.iq_audit_status
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setIqAuditStatus(Integer iqAuditStatus) {
        this.iqAuditStatus = iqAuditStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column adwl_invoice_qualification.iq_company_name
     *
     * @return the value of adwl_invoice_qualification.iq_company_name
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public String getIqCompanyName() {
        return iqCompanyName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column adwl_invoice_qualification.iq_company_name
     *
     * @param iqCompanyName the value for adwl_invoice_qualification.iq_company_name
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setIqCompanyName(String iqCompanyName) {
        this.iqCompanyName = iqCompanyName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column adwl_invoice_qualification.iq_taxer_code
     *
     * @return the value of adwl_invoice_qualification.iq_taxer_code
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public String getIqTaxerCode() {
        return iqTaxerCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column adwl_invoice_qualification.iq_taxer_code
     *
     * @param iqTaxerCode the value for adwl_invoice_qualification.iq_taxer_code
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setIqTaxerCode(String iqTaxerCode) {
        this.iqTaxerCode = iqTaxerCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column adwl_invoice_qualification.iq_company_area
     *
     * @return the value of adwl_invoice_qualification.iq_company_area
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public String getIqCompanyArea() {
        return iqCompanyArea;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column adwl_invoice_qualification.iq_company_area
     *
     * @param iqCompanyArea the value for adwl_invoice_qualification.iq_company_area
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setIqCompanyArea(String iqCompanyArea) {
        this.iqCompanyArea = iqCompanyArea;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column adwl_invoice_qualification.iq_det_address
     *
     * @return the value of adwl_invoice_qualification.iq_det_address
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public String getIqDetAddress() {
        return iqDetAddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column adwl_invoice_qualification.iq_det_address
     *
     * @param iqDetAddress the value for adwl_invoice_qualification.iq_det_address
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setIqDetAddress(String iqDetAddress) {
        this.iqDetAddress = iqDetAddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column adwl_invoice_qualification.iq_company_telphone
     *
     * @return the value of adwl_invoice_qualification.iq_company_telphone
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public String getIqCompanyTelphone() {
        return iqCompanyTelphone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column adwl_invoice_qualification.iq_company_telphone
     *
     * @param iqCompanyTelphone the value for adwl_invoice_qualification.iq_company_telphone
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setIqCompanyTelphone(String iqCompanyTelphone) {
        this.iqCompanyTelphone = iqCompanyTelphone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column adwl_invoice_qualification.iq_company_open_bank
     *
     * @return the value of adwl_invoice_qualification.iq_company_open_bank
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public String getIqCompanyOpenBank() {
        return iqCompanyOpenBank;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column adwl_invoice_qualification.iq_company_open_bank
     *
     * @param iqCompanyOpenBank the value for adwl_invoice_qualification.iq_company_open_bank
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setIqCompanyOpenBank(String iqCompanyOpenBank) {
        this.iqCompanyOpenBank = iqCompanyOpenBank;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column adwl_invoice_qualification.iq_open_bank_account
     *
     * @return the value of adwl_invoice_qualification.iq_open_bank_account
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public String getIqOpenBankAccount() {
        return iqOpenBankAccount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column adwl_invoice_qualification.iq_open_bank_account
     *
     * @param iqOpenBankAccount the value for adwl_invoice_qualification.iq_open_bank_account
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setIqOpenBankAccount(String iqOpenBankAccount) {
        this.iqOpenBankAccount = iqOpenBankAccount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column adwl_invoice_qualification.iq_bussiness_license_pic
     *
     * @return the value of adwl_invoice_qualification.iq_bussiness_license_pic
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public String getIqBussinessLicensePic() {
        return iqBussinessLicensePic;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column adwl_invoice_qualification.iq_bussiness_license_pic
     *
     * @param iqBussinessLicensePic the value for adwl_invoice_qualification.iq_bussiness_license_pic
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setIqBussinessLicensePic(String iqBussinessLicensePic) {
        this.iqBussinessLicensePic = iqBussinessLicensePic;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column adwl_invoice_qualification.iq_otherz_pic
     *
     * @return the value of adwl_invoice_qualification.iq_otherz_pic
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public String getIqOtherzPic() {
        return iqOtherzPic;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column adwl_invoice_qualification.iq_otherz_pic
     *
     * @param iqOtherzPic the value for adwl_invoice_qualification.iq_otherz_pic
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setIqOtherzPic(String iqOtherzPic) {
        this.iqOtherzPic = iqOtherzPic;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column adwl_invoice_qualification.iq_audit_id
     *
     * @return the value of adwl_invoice_qualification.iq_audit_id
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public Long getIqAuditId() {
        return iqAuditId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column adwl_invoice_qualification.iq_audit_id
     *
     * @param iqAuditId the value for adwl_invoice_qualification.iq_audit_id
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setIqAuditId(Long iqAuditId) {
        this.iqAuditId = iqAuditId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column adwl_invoice_qualification.iq_audit_person
     *
     * @return the value of adwl_invoice_qualification.iq_audit_person
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public String getIqAuditPerson() {
        return iqAuditPerson;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column adwl_invoice_qualification.iq_audit_person
     *
     * @param iqAuditPerson the value for adwl_invoice_qualification.iq_audit_person
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setIqAuditPerson(String iqAuditPerson) {
        this.iqAuditPerson = iqAuditPerson;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column adwl_invoice_qualification.iq_yn
     *
     * @return the value of adwl_invoice_qualification.iq_yn
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public Integer getIqYn() {
        return iqYn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column adwl_invoice_qualification.iq_yn
     *
     * @param iqYn the value for adwl_invoice_qualification.iq_yn
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setIqYn(Integer iqYn) {
        this.iqYn = iqYn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column adwl_invoice_qualification.create_datetime
     *
     * @return the value of adwl_invoice_qualification.create_datetime
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public String getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column adwl_invoice_qualification.create_datetime
     *
     * @param createDatetime the value for adwl_invoice_qualification.create_datetime
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setCreateDatetime(String createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column adwl_invoice_qualification.update_datetime
     *
     * @return the value of adwl_invoice_qualification.update_datetime
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public String getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column adwl_invoice_qualification.update_datetime
     *
     * @param updateDatetime the value for adwl_invoice_qualification.update_datetime
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setUpdateDatetime(String updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column adwl_invoice_qualification.audit_datetime
     *
     * @return the value of adwl_invoice_qualification.audit_datetime
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public String getAuditDatetime() {
        return auditDatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column adwl_invoice_qualification.audit_datetime
     *
     * @param auditDatetime the value for adwl_invoice_qualification.audit_datetime
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setAuditDatetime(String auditDatetime) {
        this.auditDatetime = auditDatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column adwl_invoice_qualification.iq_reserve_one
     *
     * @return the value of adwl_invoice_qualification.iq_reserve_one
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public Integer getIqReserveOne() {
        return iqReserveOne;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column adwl_invoice_qualification.iq_reserve_one
     *
     * @param iqReserveOne the value for adwl_invoice_qualification.iq_reserve_one
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setIqReserveOne(Integer iqReserveOne) {
        this.iqReserveOne = iqReserveOne;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column adwl_invoice_qualification.iq_reserve_two
     *
     * @return the value of adwl_invoice_qualification.iq_reserve_two
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public String getIqReserveTwo() {
        return iqReserveTwo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column adwl_invoice_qualification.iq_reserve_two
     *
     * @param iqReserveTwo the value for adwl_invoice_qualification.iq_reserve_two
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setIqReserveTwo(String iqReserveTwo) {
        this.iqReserveTwo = iqReserveTwo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column adwl_invoice_qualification.iq_reserve_three
     *
     * @return the value of adwl_invoice_qualification.iq_reserve_three
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public String getIqReserveThree() {
        return iqReserveThree;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column adwl_invoice_qualification.iq_reserve_three
     *
     * @param iqReserveThree the value for adwl_invoice_qualification.iq_reserve_three
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setIqReserveThree(String iqReserveThree) {
        this.iqReserveThree = iqReserveThree;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column adwl_invoice_qualification.demo
     *
     * @return the value of adwl_invoice_qualification.demo
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public String getDemo() {
        return demo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column adwl_invoice_qualification.demo
     *
     * @param demo the value for adwl_invoice_qualification.demo
     *
     * @abatorgenerated Wed Jan 02 16:59:49 CST 2019
     */
    public void setDemo(String demo) {
        this.demo = demo;
    }
}